---
title: "Mock_contaminatie_analyse_Stijn"
author: "Stijn Teunissen (24753)"
date: "`r Sys.Date()`"
output: html_document
---

```{r , eval=TRUE, echo=FALSE, include=FALSE, message=FALSE, warning=FALSE}
# set optional parameters
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE, 
                      message = FALSE)
options(scipen = 999, digits = 3)
```

```{r setup, eval=TRUE, echo=FALSE, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_knit$set(root.dir = "/Users/stijnteunissen/OneDrive - Wetsus/General/data/")
```

```{r install packages, eval=TRUE, echo=FALSE, include=FALSE, message=FALSE, warning=FALSE}
# install packages
if (!requireNamespace("phyloseq", quietly = TRUE)){BiocManager::install("phyloseq")}
if (!requireNamespace("qiime2R", quietly = TRUE)){devtools::install_github("jbisanz/qiime2R")}
if (!requireNamespace("tidyverse", quietly = TRUE)){devtools::install_github("tidyverse")}
if (!requireNamespace("magrittr", quietly = TRUE)){install.packages("magrittr")}
if (!requireNamespace("devtools", quietly = TRUE)){install.packages("devtools")}
if (!requireNamespace("here", quietly = TRUE)){install.packages("here")}
if (!requireNamespace("openxlsx", quietly = TRUE)){install.packages("openxlsx")}
if (!requireNamespace("ape", quietly = TRUE)){install.packages("ape")}
if (!requireNamespace("ggtext", quietly = TRUE)){install.packages("ggtext")}
if (!requireNamespace("cowplot", quietly = TRUE)){install.packages("cowplot")}
if (!requireNamespace("RColorBrewer", quietly = TRUE)){install.packages("RColorBrewer")}
if (!requireNamespace("microbiome", quietly = TRUE)){install.packages("microbiome")}
if (!requireNamespace("lme4", quietly = TRUE)){install.packages("lme4")}
if (!requireNamespace("lmerTest", quietly = TRUE)){install.packages("lmerTest")}
if (!requireNamespace("decontam", quietly = TRUE)){install.packages("decontam")}
if (!requireNamespace("ampvis2", quietly = TRUE)){install.packages("ampvis2")}
if (!requireNamespace("glue", quietly = TRUE)){install.packages("glue")}
if (!requireNamespace("lubridate", quietly = TRUE)){install.packages("lubridate")}
if (!requireNamespace("DECIPHER", quietly = TRUE)){install.packages("DECIPHER")}
if (!requireNamespace("ensembleTax", quietly = TRUE)){install.packages("ensembleTax")}
if (!requireNamespace("lmerTest", quietly = TRUE)){install.packages("lmerTest")}
if (!requireNamespace("brewer.pal", quietly = TRUE)){install.packages("brewer.pal")}
if (!requireNamespace("scales", quietly = TRUE)){install.packages("scales")}
if (!requireNamespace("viridis", quietly = TRUE)){install.packages("viridis")}
if (!requireNamespace("ggrepel", quietly = TRUE)){install.packages("ggrepel")}
```

```{r library loading, eval=TRUE, echo=TRUE, include=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
# load required packages
library(phyloseq)
library(qiime2R)
library(tidyverse)
library(magrittr)
library(devtools)
library(here)
library(openxlsx)
library(ape)
library(ggtext)
library(cowplot)
library(RColorBrewer)
library(microbiome)
library(lme4)
library(lmerTest)
library(decontam)
library(ampvis2)
library(glue)
library(lubridate)
library(DECIPHER)
library(ensembleTax)
library(lmerTest)
library(RColorBrewer)
library(scales)
library(viridis)
library(ggrepel)
```

```{r project organization, message=F, echo=F, eval=T, warning=F, include=F, cache=T}

# project name
proj = "STEU_Contamination_analyse"

# create directories
if(!dir.exists("figures")){dir.create("figures")}
if(!dir.exists("output_data")){dir.create("output_data")} 
if(!dir.exists("scripts")){dir.create("scripts")} 
if(!dir.exists("scripts/QIIME2")){dir.create("scripts/QIIME2")} 
```


```{r import data, eval=TRUE, echo=TRUE, include=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
# Script cleaning data
source("../scripts/tax_clean_updated.R")

# Wetsus Data 

#creating phyloseq objects for BKIS_proj1_Q16705
metadata = read.delim("Wetsus_data/BKIS_proj1_Q16705/input_data/BKIS_proj1_Q16705_metadata.tsv", header=T, sep = "\t") 
colnames(metadata)[1] =  gsub(colnames(metadata)[1], pattern = "X.", "SampleID")
metadata = sample_data(metadata)
sample_names(metadata) = metadata$SampleID

physeq_BKIS_proj1_Q16705 = qza_to_phyloseq(
  features = "Wetsus_data/BKIS_proj1_Q16705/input_data/BKIS_16S_515F_926R_08092023_Q16705_BKIS_table.qza",
  tree = "Wetsus_data/BKIS_proj1_Q16705/input_data/BKIS_16S_515F_926R_08092023_Q16705_BKIS_rooted-tree.qza",
  taxonomy = "Wetsus_data/BKIS_proj1_Q16705/input_data/BKIS_16S_515F_926R_08092023_Q16705_BKIS_silva-138-99-nb-classifier.qza",
  )
sample_data(physeq_BKIS_proj1_Q16705)  = sample_data(metadata)

sample_data(physeq_BKIS_proj1_Q16705)$read_count=sample_sums(physeq_BKIS_proj1_Q16705)

physeq_BKIS_proj1_Q16705 = tax_clean(physeq_BKIS_proj1_Q16705)


#creating phyloseq objects for OBER_proj3_Q15250
metadata = read.delim("Wetsus_data/OBER_proj3_Q15250/input_data/OBER_proj3_Q15250_metadata.tsv", header=T, sep = "\t") 
colnames(metadata)[1] =  gsub(colnames(metadata)[1], pattern = "X.", "SampleID")
metadata = sample_data(metadata)
sample_names(metadata) = metadata$SampleID

physeq_OBER_proj3_Q15250 = qza_to_phyloseq(
  features = "Wetsus_data/OBER_proj3_Q15250/input_data/OBER_16S_515F926R_Q15250_20220803_table.qza",
  tree = "Wetsus_data/OBER_proj3_Q15250/input_data/OBER_16S_515F926R_Q15250_20220803_rooted-tree.qza",
  taxonomy = "Wetsus_data/OBER_proj3_Q15250/input_data/OBER_16S_515F926R_Q15250_20220803_taxonomy_NB_classifier_SILVA_132_99_16S_515F-926R_QIIME2-2019.10.qza",
  )
sample_data(physeq_OBER_proj3_Q15250)  = sample_data(metadata)

sample_data(physeq_OBER_proj3_Q15250)$read_count=sample_sums(physeq_OBER_proj3_Q15250)

physeq_OBER_proj3_Q15250 = tax_clean(physeq_OBER_proj3_Q15250)

#creating phyloseq objects for OSOJ_proj3_Q16374
metadata = read.delim("Wetsus_data/OSOJ_proj3_Q16374_16S/input_data/OSOJ_proj3_Q16374_metadata.tsv", header=T, sep = "\t") 
colnames(metadata)[1] =  gsub(colnames(metadata)[1], pattern = "X.", "SampleID")
metadata = sample_data(metadata)
sample_names(metadata) = metadata$SampleID

physeq_OSOJ_proj3_Q16374 = qza_to_phyloseq(
  features = "Wetsus_data/OSOJ_proj3_Q16374_16S/input_data/OSOJ_16S_515F_926R_20230425_Q16347_table.qza",
  tree = "Wetsus_data/OSOJ_proj3_Q16374_16S/input_data/OSOJ_16S_515F_926R_20230425_Q16347_rooted-tree.qza",
  taxonomy = "Wetsus_data/OSOJ_proj3_Q16374_16S/input_data/OSOJ_16S_515F_926R_20230425_Q16347_silva-138-99-nb-classifier.qza",
  )
sample_data(physeq_OSOJ_proj3_Q16374)  = sample_data(metadata)

sample_data(physeq_OSOJ_proj3_Q16374)$read_count=sample_sums(physeq_OSOJ_proj3_Q16374)

physeq_OSOJ_proj3_Q16374 = tax_clean(physeq_OSOJ_proj3_Q16374)

#creating phyloseq objects for OSOJ_proj4_Q17230
metadata = read.delim("Wetsus_data/OSOJ_proj4_Q17230/OSOJ_16S_515F_926R_02202024_Q17230_OSOJ/OSOJ_proj4_Q17230_metadata.tsv", header=T, sep = "\t") 
colnames(metadata)[1] =  gsub(colnames(metadata)[1], pattern = "X.", "SampleID")
metadata = sample_data(metadata)
sample_names(metadata) = metadata$SampleID

physeq_OSOJ_proj4_Q17230 = qza_to_phyloseq(
  features = "Wetsus_data/OSOJ_proj4_Q17230/OSOJ_16S_515F_926R_02202024_Q17230_OSOJ/OSOJ_16S_515F_926R_02202024_Q17230_OSOJ_table.qza",
  tree = "Wetsus_data/OSOJ_proj4_Q17230/OSOJ_16S_515F_926R_02202024_Q17230_OSOJ/OSOJ_16S_515F_926R_02202024_Q17230_OSOJ_rooted-tree.qza",
  taxonomy = "Wetsus_data/OSOJ_proj4_Q17230/OSOJ_16S_515F_926R_02202024_Q17230_OSOJ/OSOJ_16S_515F_926R_02202024_Q17230_OSOJ_silva-138-99-nb-classifier.qza",
  )
sample_data(physeq_OSOJ_proj4_Q17230)  = sample_data(metadata)

sample_data(physeq_OSOJ_proj4_Q17230)$read_count=sample_sums(physeq_OSOJ_proj4_Q17230)

physeq_OSOJ_proj4_Q17230 = tax_clean(physeq_OSOJ_proj4_Q17230)

#creating phyloseq objects for OSOJ_proj5_Q17229
metadata = read.delim("Wetsus_data/OSOJ_proj5_Q17229/OSOJ_16S_515F_926R_02202024_Q17229_OSOJ/OSOJ_proj5_Q17229_metadata.tsv", header=T, sep = "\t") 
colnames(metadata)[1] =  gsub(colnames(metadata)[1], pattern = "X.", "SampleID")
metadata = sample_data(metadata)
sample_names(metadata) = metadata$SampleID

physeq_OSOJ_proj5_Q17229 = qza_to_phyloseq(
  features = "Wetsus_data/OSOJ_proj5_Q17229/OSOJ_16S_515F_926R_02202024_Q17229_OSOJ/OSOJ_16S_515F_926R_02202024_Q17229_OSOJ_table.qza",
  tree = "Wetsus_data/OSOJ_proj5_Q17229/OSOJ_16S_515F_926R_02202024_Q17229_OSOJ/OSOJ_16S_515F_926R_02202024_Q17229_OSOJ_rooted-tree.qza",
  taxonomy = "Wetsus_data/OSOJ_proj5_Q17229/OSOJ_16S_515F_926R_02202024_Q17229_OSOJ/OSOJ_16S_515F_926R_02202024_Q17229_OSOJ_silva-138-99-nb-classifier.qza",
  )
sample_data(physeq_OSOJ_proj5_Q17229)  = sample_data(metadata)

sample_data(physeq_OSOJ_proj5_Q17229)$read_count=sample_sums(physeq_OSOJ_proj5_Q17229)

physeq_OSOJ_proj5_Q17229 = tax_clean(physeq_OSOJ_proj5_Q17229)

#creating phyloseq objects for SHSU_proj1_Q17228
metadata = read.delim("Wetsus_data/SHSU_proj1_Q17228/SHSU_16S_515F_926R_02202024_Q17228_SHSU/SHSU_proj1_Q17228_metadata.tsv", header=T, sep = "\t") 
colnames(metadata)[1] =  gsub(colnames(metadata)[1], pattern = "X.", "SampleID")
metadata = sample_data(metadata)
sample_names(metadata) = metadata$SampleID

physeq_SHSU_proj1_Q17228 = qza_to_phyloseq(
  features = "Wetsus_data/SHSU_proj1_Q17228/SHSU_16S_515F_926R_02202024_Q17228_SHSU/SHSU_16S_515F_926R_02202024_Q17228_SHSU_table.qza",
  tree = "Wetsus_data/SHSU_proj1_Q17228/SHSU_16S_515F_926R_02202024_Q17228_SHSU/SHSU_16S_515F_926R_02202024_Q17228_SHSU_rooted-tree.qza",
  taxonomy = "Wetsus_data/SHSU_proj1_Q17228/SHSU_16S_515F_926R_02202024_Q17228_SHSU/SHSU_16S_515F_926R_02202024_Q17228_SHSU_silva-138-99-nb-classifier.qza",
  )
sample_data(physeq_SHSU_proj1_Q17228)  = sample_data(metadata)

sample_data(physeq_SHSU_proj1_Q17228)$read_count=sample_sums(physeq_SHSU_proj1_Q17228)

physeq_SHSU_proj1_Q17228 = tax_clean(physeq_SHSU_proj1_Q17228)

#creating phyloseq objects for YLUO_projx_Q12374
metadata = read.delim("Wetsus_data/YLUO_projx_Q12374//YLUO_projx_Q12374_49_89_metadata.tsv", header=T, sep = "\t") 
colnames(metadata)[1] =  gsub(colnames(metadata)[1], pattern = "X.", "SampleID")
metadata = sample_data(metadata)
sample_names(metadata) = metadata$SampleID

physeq_YLUO_projx_Q12374 = qza_to_phyloseq(
  features = "Wetsus_data/YLUO_projx_Q12374/YLUO_BAC_49_89_20200409_table.qza",
  tree = "Wetsus_data/YLUO_projx_Q12374/YLUO_BAC_49_89_20200409_rooted-tree.qza",
  taxonomy = "Wetsus_data/YLUO_projx_Q12374//YLUO_BAC_49_89_20200409_taxonomy_NB_Silva132_99-338F-806R_classifier.qza",
  )
sample_data(physeq_YLUO_projx_Q12374)  = sample_data(metadata)

sample_data(physeq_YLUO_projx_Q12374)$read_count=sample_sums(physeq_YLUO_projx_Q12374)

physeq_YLUO_projx_Q12374 = tax_clean(physeq_YLUO_projx_Q12374)

#creating phyloseq objects for YXIN_proj1_Q16712
metadata = read.delim("Wetsus_data/YXIN_proj1_Q16712/input_data/YXIN_proj1_Q16712_metadata.tsv", header=T, sep = "\t") 
colnames(metadata)[1] =  gsub(colnames(metadata)[1], pattern = "X.", "SampleID")
metadata = sample_data(metadata)
sample_names(metadata) = metadata$SampleID

physeq_YXIN_proj1_Q16712 = qza_to_phyloseq(
  features = "Wetsus_data/YXIN_proj1_Q16712/input_data/XYIN_16S_515F_926R_07092023_Q16712_XYIN_table.qza",
  tree = "Wetsus_data/YXIN_proj1_Q16712/input_data/XYIN_16S_515F_926R_07092023_Q16712_XYIN_rooted-tree.qza",
  taxonomy = "Wetsus_data/YXIN_proj1_Q16712/input_data/XYIN_16S_515F_926R_07092023_Q16712_XYIN_silva-138-99-nb-classifier.qza",
  )
sample_data(physeq_YXIN_proj1_Q16712)  = sample_data(metadata)

sample_data(physeq_YXIN_proj1_Q16712)$read_count=sample_sums(physeq_YXIN_proj1_Q16712)

physeq_YXIN_proj1_Q16712 = tax_clean(physeq_YXIN_proj1_Q16712)

# # External data
# #creating phyloseq objects for PRJEB34118
# metadata = read.delim("External_data/PRJEB34118/PRJEB34118_metadata.tsv", header=T, sep = "\t") 
# colnames(metadata)[1] =  gsub(colnames(metadata)[1], pattern = "X.", "SampleID")
# metadata = sample_data(metadata)
# sample_names(metadata) = metadata$SampleID
# 
# physeq_PRJEB34118 = qza_to_phyloseq(
#   features = "External_data/PRJEB34118/PRJEB34118_table.qza",
#   tree = "External_data/PRJEB34118/PRJEB34118_rooted-tree.qza",
#   taxonomy = "External_data/PRJEB34118/PRJEB34118_silva-138-99-nb-classifier.qza",
#   )
# sample_data(physeq_PRJEB34118)  = sample_data(metadata)
# 
# sample_data(physeq_PRJEB34118)$read_count=sample_sums(physeq_PRJEB34118)
# 
# physeq_PRJEB34118 = tax_clean(physeq_PRJEB34118)
# 
# #creating phyloseq objects for PRJEB36253
# metadata = read.delim("External_data/PRJEB36253/PRJEB36253_metadata.tsv", header=T, sep = "\t") 
# colnames(metadata)[1] =  gsub(colnames(metadata)[1], pattern = "X.", "SampleID")
# metadata = sample_data(metadata)
# sample_names(metadata) = metadata$SampleID
# 
# physeq_PRJEB36253 = qza_to_phyloseq(
#   features = "External_data/PRJEB36253/PRJEB36253_table.qza",
#   tree = "External_data/PRJEB36253/PRJEB36253_rooted-tree.qza",
#   taxonomy = "External_data/PRJEB36253/PRJEB36253_silva-138-99-nb-classifier.qza",
#   )
# sample_data(physeq_PRJEB36253)  = sample_data(metadata)
# 
# sample_data(physeq_PRJEB36253)$read_count=sample_sums(physeq_PRJEB36253)
# 
# physeq_PRJEB36253 = tax_clean(physeq_PRJEB36253)
# 
# #creating phyloseq objects for PRJNA648321
# metadata = read.delim("External_data/PRJNA648321/PRJNA648321_metadata.tsv", header=T, sep = "\t") 
# colnames(metadata)[1] =  gsub(colnames(metadata)[1], pattern = "X.", "SampleID")
# metadata = sample_data(metadata)
# sample_names(metadata) = metadata$SampleID
# 
# physeq_PRJNA648321 = qza_to_phyloseq(
#   features = "External_data/PRJNA648321/PRJNA648321_table.qza",
#   tree = "External_data/PRJNA648321/PRJNA648321_rooted-tree.qza",
#   taxonomy = "External_data/PRJNA648321/PRJNA648321_silva-138-99-nb-classifier.qza",
#   )
# sample_data(physeq_PRJNA648321)  = sample_data(metadata)
# 
# sample_data(physeq_PRJNA648321)$read_count=sample_sums(physeq_PRJNA648321)
# 
# physeq_PRJNA648321 = tax_clean(physeq_PRJNA648321)
# 
# #creating phyloseq objects for PRJNA862376
# metadata = read.delim("External_data/PRJNA862376//PRJNA862376_metadata.tsv", header=T, sep = "\t") 
# colnames(metadata)[1] =  gsub(colnames(metadata)[1], pattern = "X.", "SampleID")
# metadata = sample_data(metadata)
# sample_names(metadata) = metadata$SampleID
# 
# physeq_PRJNA862376 = qza_to_phyloseq(
#   features = "External_data/PRJNA862376/PRJNA862376_table.qza",
#   tree = "External_data/PRJNA862376/PRJNA862376_rooted-tree.qza",
#   taxonomy = "External_data/PRJNA862376/PRJNA862376_silva-138-99-nb-classifier.qza",
#   )
# sample_data(physeq_PRJNA862376)  = sample_data(metadata)
# 
# sample_data(physeq_PRJNA862376)$read_count=sample_sums(physeq_PRJNA862376)
# 
# physeq_PRJNA862376 = tax_clean(physeq_PRJNA862376)
```

```{r bind data, eval=TRUE, echo=TRUE, include=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
# bind different studies

# Wetsus data

# BKIS_proj1_Q16705
BKIS_proj1_Q16705 = 
  physeq_BKIS_proj1_Q16705 %>% 
  transform_sample_counts(., fun = function(x) x/sum(x)*100) %>% 
  #prune_taxa(taxa_sums(.)>0.01, .) %>% 
  psmelt() %>% 
  as_tibble() %>% 
  mutate(study = "BKIS_proj1_Q16705")

# filter mock out and at prevalence 
physeq_BKIS_proj1_Q16705_no_mock = 
physeq_BKIS_proj1_Q16705 %>% 
  subset_samples(., Sample_mock == "sample") %>% 
  prune_taxa(taxa_sums(.)>0, .) %>% 
  microbiome::prevalence() %>% 
  data.frame(prevalence = .) %>%
  tibble::rownames_to_column(var = "OTU") 

BKIS_proj1_Q16705_prevalence =
  left_join(BKIS_proj1_Q16705, physeq_BKIS_proj1_Q16705_no_mock, by = "OTU") %>% 
  select(OTU, Sample, Abundance, prevalence, everything())

# OBER_proj3_Q15250
OBER_proj3_Q15250 = 
  physeq_OBER_proj3_Q15250 %>% 
  transform_sample_counts(., fun = function(x) x/sum(x)*100) %>% 
  #prune_taxa(taxa_sums(.)>0.01, .) %>% # 
  psmelt() %>% 
  as_tibble() %>% 
  mutate(study = "OBER_proj3_Q15250")

# filter mock out and at prevalence 
physeq_OBER_proj3_Q15250_no_mock = 
physeq_OBER_proj3_Q15250 %>% 
  subset_samples(., Sample_mock == "sample") %>% 
  prune_taxa(taxa_sums(.)>0, .) %>% 
  microbiome::prevalence() %>% 
  data.frame(prevalence = .) %>%
  tibble::rownames_to_column(var = "OTU") 

OBER_proj3_Q15250_prevalence =
  left_join(OBER_proj3_Q15250, physeq_OBER_proj3_Q15250_no_mock, by = "OTU") %>% 
  select(OTU, Sample, Abundance, prevalence, everything())

# OSOJ_proj3_Q16374
OSOJ_proj3_Q16374 = 
  physeq_OSOJ_proj3_Q16374 %>% 
  transform_sample_counts(., fun = function(x) x/sum(x)*100) %>% 
  #prune_taxa(taxa_sums(.)>0.01, .) %>% # 
  psmelt() %>% 
  as_tibble() %>% 
  mutate(study = "OSOJ_proj3_Q16374")

# filter mock out and at prevalence 
physeq_OSOJ_proj3_Q16374_no_mock = 
physeq_OSOJ_proj3_Q16374 %>% 
  subset_samples(., Sample_mock == "sample") %>% 
  prune_taxa(taxa_sums(.)>0, .) %>% 
  microbiome::prevalence() %>% 
  data.frame(prevalence = .) %>%
  tibble::rownames_to_column(var = "OTU") 

OSOJ_proj3_Q16374_prevalence =
  left_join(OSOJ_proj3_Q16374, physeq_OSOJ_proj3_Q16374_no_mock, by = "OTU") %>% 
  select(OTU, Sample, Abundance, prevalence, everything())

# OSOJ_proj4_Q17230
OSOJ_proj4_Q17230 = 
  physeq_OSOJ_proj4_Q17230 %>% 
  transform_sample_counts(., fun = function(x) x/sum(x)*100) %>% 
  #prune_taxa(taxa_sums(.)>0.01, .) %>% # 
  psmelt() %>% 
  as_tibble() %>% 
  mutate(study = "OSOJ_proj4_Q17230")

# filter mock out and at prevalence 
physeq_OSOJ_proj4_Q17230_no_mock = 
physeq_OSOJ_proj4_Q17230 %>% 
  subset_samples(., Sample_mock == "sample") %>% 
  prune_taxa(taxa_sums(.)>0, .) %>% 
  microbiome::prevalence() %>% 
  data.frame(prevalence = .) %>%
  tibble::rownames_to_column(var = "OTU") 

OSOJ_proj4_Q17230_prevalence =
  left_join(OSOJ_proj4_Q17230, physeq_OSOJ_proj4_Q17230_no_mock, by = "OTU") %>% 
  select(OTU, Sample, Abundance, prevalence, everything())

# OSOJ_proj5_Q17229
OSOJ_proj5_Q17229 = 
  physeq_OSOJ_proj5_Q17229 %>% 
  transform_sample_counts(., fun = function(x) x/sum(x)*100) %>% 
  #prune_taxa(taxa_sums(.)>0.01, .) %>% # 
  psmelt() %>% 
  as_tibble() %>% 
  mutate(study = "OSOJ_proj5_Q17229")

# filter mock out and at prevalence 
physeq_OSOJ_proj5_Q17229_no_mock = 
physeq_OSOJ_proj5_Q17229 %>% 
  subset_samples(., Sample_mock == "sample") %>% 
  prune_taxa(taxa_sums(.)>0, .) %>% 
  microbiome::prevalence() %>% 
  data.frame(prevalence = .) %>%
  tibble::rownames_to_column(var = "OTU") 

OSOJ_proj5_Q17229_prevalence =
  left_join(OSOJ_proj5_Q17229, physeq_OSOJ_proj5_Q17229_no_mock, by = "OTU") %>% 
  select(OTU, Sample, Abundance, prevalence, everything())

# SHSU_proj1_Q17228
SHSU_proj1_Q17228 = 
  physeq_SHSU_proj1_Q17228 %>% 
  transform_sample_counts(., fun = function(x) x/sum(x)*100) %>% 
  #prune_taxa(taxa_sums(.)>0.01, .) %>% # 
  psmelt() %>% 
  as_tibble() %>% 
  mutate(study = "SHSU_proj1_Q17228")

# filter mock out and at prevalence 
physeq_SHSU_proj1_Q17228_no_mock = 
physeq_SHSU_proj1_Q17228 %>% 
  subset_samples(., Sample_mock == "sample") %>% 
  prune_taxa(taxa_sums(.)>0, .) %>% 
  microbiome::prevalence() %>% 
  data.frame(prevalence = .) %>%
  tibble::rownames_to_column(var = "OTU") 

SHSU_proj1_Q17228_prevalence =
  left_join(SHSU_proj1_Q17228, physeq_SHSU_proj1_Q17228_no_mock, by = "OTU") %>% 
  select(OTU, Sample, Abundance, prevalence, everything())

# YLUO_projx_Q12374
YLUO_projx_Q12374 = 
  physeq_YLUO_projx_Q12374 %>% 
  transform_sample_counts(., fun = function(x) x/sum(x)*100) %>% 
  #prune_taxa(taxa_sums(.)>0.01, .) %>% # 
  psmelt() %>% 
  as_tibble() %>% 
  mutate(study = "YLUO_projx_Q12374")

# filter mock out and at prevalence 
physeq_YLUO_projx_Q12374_no_mock = 
physeq_YLUO_projx_Q12374 %>% 
  subset_samples(., Sample_mock == "sample") %>% 
  prune_taxa(taxa_sums(.)>0, .) %>% 
  microbiome::prevalence() %>% 
  data.frame(prevalence = .) %>%
  tibble::rownames_to_column(var = "OTU") 

YLUO_projx_Q12374_prevalence =
  left_join(YLUO_projx_Q12374, physeq_YLUO_projx_Q12374_no_mock, by = "OTU") %>% 
  select(OTU, Sample, Abundance, prevalence, everything())

# YXIN_proj1_Q16712
YXIN_proj1_Q16712 = 
  physeq_YXIN_proj1_Q16712 %>% 
  transform_sample_counts(., fun = function(x) x/sum(x)*100) %>% 
  #prune_taxa(taxa_sums(.)>0.01, .) %>% # 
  psmelt() %>% 
  as_tibble() %>% 
  mutate(study = "YXIN_proj1_Q16712")

# filter mock out and at prevalence 
physeq_YXIN_proj1_Q16712_no_mock = 
physeq_YXIN_proj1_Q16712 %>% 
  subset_samples(., Sample_mock == "sample") %>% 
  prune_taxa(taxa_sums(.)>0, .) %>% 
  microbiome::prevalence() %>% 
  data.frame(prevalence = .) %>%
  tibble::rownames_to_column(var = "OTU") 

YXIN_proj1_Q16712_prevalence =
  left_join(YXIN_proj1_Q16712, physeq_YXIN_proj1_Q16712_no_mock, by = "OTU") %>% 
  select(OTU, Sample, Abundance, prevalence, everything()) 

# # External data
# 
# # PRJEB34118
# PRJEB34118 = 
#   physeq_PRJEB34118 %>% 
#   transform_sample_counts(., fun = function(x) x/sum(x)*100) %>% 
#   #prune_taxa(taxa_sums(.)>0.01, .) %>% # 
#   psmelt() %>% 
#   as_tibble() %>% 
#   mutate(study = "PRJEB34118")
# 
# # filter mock out and at prevalence 
# physeq_PRJEB34118_no_mock = 
# physeq_PRJEB34118 %>% 
#   subset_samples(., Sample_mock == "sample") %>% 
#   prune_taxa(taxa_sums(.)>0, .) %>% 
#   microbiome::prevalence() %>% 
#   data.frame(prevalence = .) %>%
#   tibble::rownames_to_column(var = "OTU") 
# 
# PRJEB34118_prevalence =
#   left_join(PRJEB34118, physeq_PRJEB34118_no_mock, by = "OTU") %>% 
#   select(OTU, Sample, Abundance, prevalence, everything()) 
# 
# # PRJEB36253
# PRJEB36253 = 
#   physeq_PRJEB36253 %>% 
#   transform_sample_counts(., fun = function(x) x/sum(x)*100) %>% 
#   #prune_taxa(taxa_sums(.)>0.01, .) %>% # 
#   psmelt() %>% 
#   as_tibble() %>% 
#   mutate(study = "PRJEB36253")
# 
# # filter mock out and at prevalence 
# physeq_PRJEB36253_no_mock = 
# physeq_PRJEB36253 %>% 
#   subset_samples(., Sample_mock == "sample") %>% 
#   prune_taxa(taxa_sums(.)>0, .) %>% 
#   microbiome::prevalence() %>% 
#   data.frame(prevalence = .) %>%
#   tibble::rownames_to_column(var = "OTU") 
# 
# PRJEB36253_prevalence =
#   left_join(PRJEB36253, physeq_PRJEB36253_no_mock, by = "OTU") %>% 
#   select(OTU, Sample, Abundance, prevalence, everything())
# 
# # PRJNA648321
# PRJNA648321 = 
#   physeq_PRJNA648321 %>% 
#   transform_sample_counts(., fun = function(x) x/sum(x)*100) %>% 
#   #prune_taxa(taxa_sums(.)>0.01, .) %>% # 
#   psmelt() %>% 
#   as_tibble() %>% 
#   mutate(study = "PRJNA648321")
# 
# # filter mock out and at prevalence 
# physeq_PRJNA648321_no_mock = 
# physeq_PRJNA648321 %>% 
#   subset_samples(., Sample_mock == "sample") %>% 
#   prune_taxa(taxa_sums(.)>0, .) %>% 
#   microbiome::prevalence() %>% 
#   data.frame(prevalence = .) %>%
#   tibble::rownames_to_column(var = "OTU") 
# 
# PRJNA648321_prevalence =
#   left_join(PRJNA648321, physeq_PRJNA648321_no_mock, by = "OTU") %>% 
#   select(OTU, Sample, Abundance, prevalence, everything())
# 
# # PRJNA862376
# PRJNA862376 = 
#   physeq_PRJNA862376 %>% 
#   transform_sample_counts(., fun = function(x) x/sum(x)*100) %>% 
#   #prune_taxa(taxa_sums(.)>0.01, .) %>% # 
#   psmelt() %>% 
#   as_tibble() %>% 
#   mutate(study = "PRJNA862376")
# 
# # filter mock out and at prevalence 
# physeq_PRJNA862376_no_mock = 
# physeq_PRJNA862376 %>% 
#   subset_samples(., Sample_mock == "sample") %>% 
#   prune_taxa(taxa_sums(.)>0, .) %>% 
#   microbiome::prevalence() %>% 
#   data.frame(prevalence = .) %>%
#   tibble::rownames_to_column(var = "OTU") 
# 
# PRJNA862376_prevalence =
#   left_join(PRJNA862376, physeq_PRJNA862376_no_mock, by = "OTU") %>% 
#   select(OTU, Sample, Abundance, prevalence, everything())

# List all studies 
Inhouse_wetsus_2022_studies <- list(BKIS_proj1_Q16705_prevalence, OBER_proj3_Q15250_prevalence, OSOJ_proj3_Q16374_prevalence)
bind_rows(Inhouse_wetsus_2022_studies)

Inhouse_wetsus_2023_studies <- list(BKIS_proj1_Q16705_prevalence, OSOJ_proj4_Q17230_prevalence, OSOJ_proj5_Q17229_prevalence, SHSU_proj1_Q17228_prevalence, YXIN_proj1_Q16712_prevalence)
bind_rows(Inhouse_wetsus_2023_studies)

Zymo_log10_studies <- list(YLUO_projx_Q12374_prevalence)
bind_rows(Zymo_log10_studies)

Zymo_equil_studies <- list(OBER_proj3_Q15250_prevalence) # PRJNA862376_prevalence PRJEB34118_prevalence
bind_rows(Zymo_equil_studies)

all_studies <- list(BKIS_proj1_Q16705_prevalence, OBER_proj3_Q15250_prevalence, OSOJ_proj3_Q16374_prevalence, OSOJ_proj4_Q17230_prevalence, OSOJ_proj5_Q17229_prevalence, SHSU_proj1_Q17228_prevalence, YLUO_projx_Q12374_prevalence, YXIN_proj1_Q16712_prevalence)

# Inhouse_PRJNA648321 <- list(PRJNA648321_prevalence)
# bind_rows(Inhouse_PRJNA648321)
# 
# Inhouse_PRJEB36253 <- list(PRJEB36253_prevalence)
# bind_rows(Inhouse_PRJEB36253)
```

```{r Prevalence berekenen, eval=TRUE, echo=TRUE, include=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
# Correct all studies
all_studies_corrected =
  all_studies %>% 
  lapply(function(df) {
    df %>%
  filter(Sample_mock == "sample") %>% 
  mutate(Sample = if_else(str_sub(Sample, -1)== "C", str_replace(Sample, "C$", ""), Sample)) %>% 
  group_by(across(-c(SampleID, Abundance, read_count))) %>% 
  summarise(mean_abundance = mean(Abundance), 
            mean_read_count = mean(read_count), 
            mean_dna_conc = mean(DNA_Concentration), 
            .groups = "drop") %>% 
  distinct() %>% 
  group_by(Sample, Genus, study, OTU) %>%   
  summarise(abund = sum(mean_abundance),
            readcount = sum(mean_read_count),
            dnaconc = mean(mean_dna_conc),
            .groups = "drop") %>% 
  group_by(study) %>% 
  arrange(study, desc(abund))
  })

# calculate mean, median and max abundace 
all_studies_table =
  all_studies_corrected %>% 
  lapply(function(df) {
    df %>%
  select(study, Sample, OTU, abund) %>% 
  group_by(study, OTU) %>% 
  summarise(mean_abund = mean(abund),
            median_abund = median(abund),
            max_abund = max(abund),
            .groups = "drop") %>% 
  arrange(desc(mean_abund))
  }) %>% 
  bind_rows()

# Filter the mock samples from the studies
mock_only_inhouse_2022_BKIS_proj1_Q16705 =
  all_studies %>% 
  bind_rows() %>%
  filter(study == "BKIS_proj1_Q16705") %>% 
  filter(Sample_mock == "mock") %>%
  filter(Sample != "MC23") %>% 
  filter(!(Genus %in% Inhouse2022_correct$Genus)) %>% 
  arrange(desc(Abundance)) %>% 
  select(study, OTU, Abundance, prevalence) %>% 
  inner_join(., all_studies_table, by = c("study", "OTU")) %>% 
  pivot_longer(cols = c(prevalence, mean_abund, median_abund, max_abund),names_to = "sample_char", values_to = "value")

mock_only_inhouse_2023_BKIS_proj1_Q16705 =
  all_studies %>% 
  bind_rows() %>%
  filter(study == "BKIS_proj1_Q16705") %>% 
  filter(Sample_mock == "mock") %>%
  filter(Sample != "MC22") %>% 
  filter(!(Genus %in% Inhouse2023$Genus)) %>% 
  arrange(desc(Abundance)) %>% 
  select(study, OTU, Abundance, prevalence) %>% 
  inner_join(., all_studies_table, by = c("study", "OTU")) %>% 
  pivot_longer(cols = c(prevalence, mean_abund, median_abund, max_abund),names_to = "sample_char", values_to = "value")

mock_only_inhouse_2022_OBER_proj3_Q15250 =
  all_studies %>% 
  bind_rows() %>%
  filter(study == "OBER_proj3_Q15250") %>% 
  filter(Sample_mock == "mock") %>%
  filter(Sample != "MCZ") %>% 
  filter(!(Genus %in% Inhouse2022_correct$Genus)) %>% 
  arrange(desc(Abundance)) %>% 
  select(study, OTU, Abundance, prevalence) %>% 
  inner_join(., all_studies_table, by = c("study", "OTU")) %>% 
  pivot_longer(cols = c(prevalence, mean_abund, median_abund, max_abund),names_to = "sample_char", values_to = "value")

mock_only_zymo_OBER_proj3_Q15250 =
  all_studies %>% 
  bind_rows() %>%
  filter(study == "OBER_proj3_Q15250") %>% 
  filter(Sample_mock == "mock") %>%
  filter(!Sample %in% c("MC1", "MC2")) %>% 
  filter(!(Genus %in% Zymo_equil$Genus)) %>% 
  arrange(desc(Abundance)) %>% 
  select(study, OTU, Abundance, prevalence) %>% 
  inner_join(., all_studies_table, by = c("study", "OTU")) %>% 
  pivot_longer(cols = c(prevalence, mean_abund, median_abund, max_abund),names_to = "sample_char", values_to = "value")

mock_only_OSOJ_proj3_Q16374 =
  all_studies %>% 
  bind_rows() %>%
  filter(study == "OSOJ_proj3_Q16374") %>% 
  filter(Sample_mock == "mock") %>%
  filter(!(Genus %in% Inhouse2022_correct$Genus)) %>% 
  arrange(desc(Abundance)) %>% 
  select(study, OTU, Abundance, prevalence) %>% 
  inner_join(., all_studies_table, by = c("study", "OTU")) %>% 
  pivot_longer(cols = c(prevalence, mean_abund, median_abund, max_abund),names_to = "sample_char", values_to = "value")

mock_only_OSOJ_proj4_Q17230 =
  all_studies %>% 
  bind_rows() %>%
  filter(study == "OSOJ_proj4_Q17230") %>% 
  filter(Sample_mock == "mock") %>%
  filter(!(Genus %in% Inhouse2023$Genus)) %>% 
  arrange(desc(Abundance)) %>% 
  select(study, OTU, Abundance, prevalence) %>% 
  inner_join(., all_studies_table, by = c("study", "OTU")) %>% 
  pivot_longer(cols = c(prevalence, mean_abund, median_abund, max_abund),names_to = "sample_char", values_to = "value")

mock_only_OSOJ_proj5_Q17229 =
  all_studies %>% 
  bind_rows() %>%
  filter(study == "OSOJ_proj5_Q17229") %>% 
  filter(Sample_mock == "mock") %>%
  filter(!(Genus %in% Inhouse2023$Genus)) %>% 
  arrange(desc(Abundance)) %>% 
  select(study, OTU, Abundance, prevalence) %>% 
  inner_join(., all_studies_table, by = c("study", "OTU")) %>% 
  pivot_longer(cols = c(prevalence, mean_abund, median_abund, max_abund),names_to = "sample_char", values_to = "value")

mock_only_SHSU_proj1_Q17228 =
  all_studies %>% 
  bind_rows() %>%
  filter(study == "SHSU_proj1_Q17228") %>% 
  filter(Sample_mock == "mock") %>%
  filter(!(Genus %in% Inhouse2023$Genus)) %>% 
  arrange(desc(Abundance)) %>% 
  select(study, OTU, Abundance, prevalence) %>% 
  inner_join(., all_studies_table, by = c("study", "OTU")) %>% 
  pivot_longer(cols = c(prevalence, mean_abund, median_abund, max_abund),names_to = "sample_char", values_to = "value")

mock_only_YLUO_projx_Q12374 =
  all_studies %>% 
  bind_rows() %>%
  filter(study == "YLUO_projx_Q12374") %>% 
  filter(Sample_mock == "mock") %>%
  filter(!(Genus %in% Zymo_log10$Genus)) %>% 
  arrange(desc(Abundance)) %>% 
  select(study, OTU, Abundance, prevalence) %>% 
  inner_join(., all_studies_table, by = c("study", "OTU")) %>% 
  pivot_longer(cols = c(prevalence, mean_abund, median_abund, max_abund),names_to = "sample_char", values_to = "value")

mock_only_YXIN_proj1_Q16712 =
  all_studies %>% 
  bind_rows() %>%
  filter(study == "YXIN_proj1_Q16712") %>% 
  filter(Sample_mock == "mock") %>%
  filter(!(Genus %in% Inhouse2023$Genus)) %>% 
  arrange(desc(Abundance)) %>% 
  select(study, OTU, Abundance, prevalence) %>% 
  inner_join(., all_studies_table, by = c("study", "OTU")) %>% 
  pivot_longer(cols = c(prevalence, mean_abund, median_abund, max_abund),names_to = "sample_char", values_to = "value")

# mock_only_PRJEB34118 =
#   all_studies %>% 
#   bind_rows() %>%
#   filter(study == "PRJEB34118") %>% 
#   filter(Sample_mock == "mock") %>%
#   filter(Sample != "ERR3494197") %>% 
#   filter(!(Genus %in% Zymo_equil$Genus)) %>% 
#   arrange(desc(Abundance)) %>% 
#   select(study, OTU, Abundance, prevalence) %>% 
#   inner_join(., all_studies_table, by = c("study", "OTU")) %>% 
#   pivot_longer(cols = c(prevalence, mean_abund, median_abund, max_abund),names_to = "sample_char", values_to = "value")
# 
# mock_only_PRJEB36253 =
#   all_studies %>% 
#   bind_rows() %>%
#   filter(study == "PRJEB36253") %>% 
#   filter(Sample_mock == "mock") %>%
#   filter(!Sample %in% c("?", "?")) %>% 
#   filter(!(Genus %in% Inhouse_PRJEB36253$Genus)) %>% 
#   arrange(desc(Abundance)) %>% 
#   select(study, OTU, Abundance, prevalence) %>% 
#   inner_join(., all_studies_table, by = c("study", "OTU")) %>% 
#   pivot_longer(cols = c(prevalence, mean_abund, median_abund, max_abund),names_to = "sample_char", values_to = "value")
# 
# mock_only_PRJNA648321 =
#   all_studies %>% 
#   bind_rows() %>%
#   filter(study == "PRJNA648321") %>% 
#   filter(Sample_mock == "mock") %>%
#   filter(!(Genus %in% Inhouse_PRJNA648321$Genus)) %>% 
#   arrange(desc(Abundance)) %>% 
#   select(study, OTU, Abundance, prevalence) %>% 
#   inner_join(., all_studies_table, by = c("study", "OTU")) %>% 
#   pivot_longer(cols = c(prevalence, mean_abund, median_abund, max_abund),names_to = "sample_char", values_to = "value")
# 
# mock_only_PRJNA862376 =
#   all_studies %>% 
#   bind_rows() %>%
#   filter(study == "PRJNA862376") %>% 
#   filter(Sample_mock == "mock") %>%
#   filter(!(Genus %in% Zymo_equil$Genus)) %>% 
#   arrange(desc(Abundance)) %>% 
#   select(study, OTU, Abundance, prevalence) %>% 
#   inner_join(., all_studies_table, by = c("study", "OTU")) %>% 
#   pivot_longer(cols = c(prevalence, mean_abund, median_abund, max_abund),names_to = "sample_char", values_to = "value")

# List all studies together
all_studies_list =
  list(mock_only_inhouse_2022_BKIS_proj1_Q16705, mock_only_inhouse_2023_BKIS_proj1_Q16705, mock_only_inhouse_2022_OBER_proj3_Q15250, mock_only_zymo_OBER_proj3_Q15250, mock_only_OSOJ_proj3_Q16374, mock_only_OSOJ_proj4_Q17230, mock_only_OSOJ_proj5_Q17229, mock_only_SHSU_proj1_Q17228, mock_only_YLUO_projx_Q12374, mock_only_YXIN_proj1_Q16712) %>% 
  bind_rows()

# plot prevalaence 
all_studies_plot_prevalence =
  all_studies_list %>% 
  ggplot(aes(x=value, y=Abundance, shape = sample_char)) +
  #geom_point(aes(color = study)) +
  ylim(0, 1.5) +
  stat_smooth(aes(group = study, color = study), method = "lm", se = TRUE) +
  facet_wrap(~sample_char, nrow = 2, ncol = 4, scales = "free")

ggsave("figures/plot_prevalence.pdf", plot = all_studies_plot_prevalence, width = 6, height = 4)
ggsave("figures/plot_prevalence.jpg", plot = all_studies_plot_prevalence, width = 6, height = 4)

all_studies_plot_prevalence
```

```{r sample en mock namen, eval=TRUE, echo=TRUE, include=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
# filter names of mock samples
mock_names_inhouse_wetsus_2022 = 
  Inhouse_wetsus_2022_studies %>%
  lapply(function(df) {
    df %>%
  filter(Sample_mock == "mock") %>%
  distinct(Sample)
  }) %>%
  bind_rows()

mock_names_inhouse_wetsus_2023 = 
  Inhouse_wetsus_2023_studies %>%
  lapply(function(df) {
    df %>%
  filter(Sample_mock == "mock") %>%
  distinct(Sample)
  }) %>%
  bind_rows()

mock_names_zymo_log10 = 
  Zymo_log10_studies %>%
  lapply(function(df) {
    df %>%
  filter(Sample_mock == "mock") %>%
  distinct(Sample)
  }) %>%
  bind_rows()

mock_names_zymo_equil = 
  Zymo_equil_studies %>%
  lapply(function(df) {
    df %>%
  filter(Sample_mock == "mock") %>%
  distinct(Sample)
  }) %>%
  bind_rows()

# filter sample names
sample_names_inhouse_wetsus_2022 =
  Inhouse_wetsus_2022_studies %>%
  lapply(function(df) {
    df %>%
  filter(Sample_mock == "sample") %>%
  distinct(Sample)
  }) %>%
  bind_rows()

sample_names_inhouse_wetsus_2023 = 
  Inhouse_wetsus_2023_studies %>%
  lapply(function(df) {
    df %>%
  filter(Sample_mock == "sample") %>%
  distinct(Sample)
  }) %>%
  bind_rows()

sample_names_zymo_log10 = 
  Zymo_log10_studies %>%
  lapply(function(df) {
    df %>%
  filter(Sample_mock == "sample") %>%
  distinct(Sample)
  }) %>%
  bind_rows()

sample_names_zymo_equil = 
  Zymo_equil_studies %>%
  lapply(function(df) {
    df %>%
  filter(Sample_mock == "sample") %>%
  distinct(Sample)
  }) %>%
  bind_rows()
```

```{r collors, eval=TRUE, echo=TRUE, include=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
# Table of all the different bacteria
Inhouse_wetsus_bacteria <- c("Brevibacillus", "Bacillus", "Lysinibacillus", "Bordetella", "Sphingobium", 
                             "Streptomyces", "Burkholderia-Caballeronia-Paraburkholderia")

Zymo_bacteria <- c("Listeria", "Pseudomonas", "Bacillus", "Escherichia-Shigella", 
                   "Salmonella", "Lactobacillus", "Enterococcus", "Staphylococcus")

num_inhouse_wetsus<- length(Inhouse_wetsus_bacteria)

num_zymo<- length(Zymo_bacteria)

inhouse_wetsus_colors <- brewer.pal(num_inhouse_wetsus, "Paired")
zymo_colors <- brewer.pal(num_zymo, "Paired")

color_mapping <- c(setNames(inhouse_wetsus_colors, Inhouse_wetsus_bacteria), 
                   setNames(zymo_colors, Zymo_bacteria), 
                   "Other genus" = "grey")
```

```{r mock bar plot, eval=TRUE, echo=TRUE, include=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
# barplot for mock communities

# inhouse_mock_2022
mock_only_Inhouse_wetsus_2022_samples =
  Inhouse_wetsus_2022_studies %>%
  lapply(function(df) {
    df %>%
  filter(Sample_mock == "mock") %>%
  select(OTU, Sample, everything()) %>% 
  mutate(Sample = if_else(str_sub(Sample, -1)== "C", str_replace(Sample, "C$", ""), Sample)) %>% 
  group_by(across(-c(SampleID, Abundance, read_count))) %>% 
  summarise(mean_abundance = mean(Abundance), 
            mean_read_count = mean(read_count), 
            mean_dna_conc = mean(DNA_Concentration), .groups = "drop") %>% 
  distinct() %>% 
  group_by(Sample, Genus) %>%   
  summarise(abund = sum(mean_abundance),
            readcount = sum(mean_read_count),
            dnaconc = mean(mean_dna_conc),
            .groups = "drop") %>% 
  arrange(-abund)
  }) %>% 
  bind_rows()

Inhouse_wetsus_2022_mock =
  c("Serratia", "Massilia", "Brevibacillus", "Bacillus", "Weizmannia", "Lysinibacillus", "Peribacillus", "Bordetella")

mock_only_Inhouse_wetsus_2022_samples_2 = 
  mock_only_Inhouse_wetsus_2022_samples %>% 
  filter(!Sample %in% c("MCZ", "MC23")) %>% 
  mutate(Genus = ifelse(Genus %in% Inhouse_wetsus_2022_mock, Genus, "Other genus")) %>% 
  mutate(Genus = factor(Genus, levels = c(setdiff(unique(Genus), "Other genus"), "Other genus")))

bar_plot_inhouse_wetsus_2022 =
  ggplot(mock_only_Inhouse_wetsus_2022_samples_2, aes(x = Sample , y = abund, fill = Genus)) +
  geom_bar(position= "stack", stat = "identity") +
  scale_fill_manual(values = color_mapping) +
  theme_minimal() +
  labs(title = "barplot inhouse_wetsus_2022 mock communities", x = "Sample", y = "Abundantie (%)", fill = "Genus")

ggsave("figures/bar_plot_inhouse_wetsus_2022.pdf", plot = bar_plot_inhouse_wetsus_2022, width = 6, height = 4)
ggsave("figures/bar_plot_inhouse_wetsus_2022.jpg", plot = bar_plot_inhouse_wetsus_2022, width = 6, height = 4)

bar_plot_inhouse_wetsus_2022

Genus_abundance_inhouse_wetsus_2022 = 
  mock_only_Inhouse_wetsus_2022_samples_2 %>% 
  group_by(Sample, Genus) %>%
  summarize(total_abundance = sum(abund))
#print(Genus_abundance_inhouse_wetsus_2022, n = nrow(Genus_abundance_inhouse_wetsus_2022))

# Inhouse_mock_2023
mock_only_Inhouse_wetsus_2023_samples =
Inhouse_wetsus_2023_studies %>%
  lapply(function(df) {
    df %>% 
  filter(Sample_mock == "mock") %>%
  select(OTU, Sample, everything()) %>% 
  mutate(Sample = if_else(str_sub(Sample, -1)== "C", str_replace(Sample, "C$", ""), Sample)) %>% 
  group_by(across(-c(SampleID, Abundance, read_count))) %>% 
  summarise(mean_abundance = mean(Abundance), 
            mean_read_count = mean(read_count), 
            mean_dna_conc = mean(DNA_Concentration), .groups = "drop") %>% 
  distinct() %>% 
  group_by(Sample, Genus) %>%   
  summarise(abund = sum(mean_abundance),
            readcount = sum(mean_read_count),
            dnaconc = mean(mean_dna_conc),
            .groups = "drop") %>% 
  arrange(-abund)
  }) %>% 
  bind_rows()

Inhouse_wetsus_2023_mock =
  c("Brevibacillus", "Weizmannia", "Lysinibacillus", "Bacillus", "Sphingobium", "Serratia", "Streptomyces", "Burkholderia")

mock_only_Inhouse_wetsus_2023_samples_2 = 
  mock_only_Inhouse_wetsus_2023_samples %>% 
  filter(!Sample %in% c("MC22")) %>% 
  mutate(Genus = ifelse(Genus %in% Inhouse_wetsus_2023_mock, Genus, "Other genus")) %>% 
  mutate(Genus = factor(Genus, levels = c(setdiff(unique(Genus), "Other genus"), "Other genus")))

bar_plot_inhouse_wetsus_2023 =
  ggplot(mock_only_Inhouse_wetsus_2023_samples_2, aes(x = Sample , y = abund, fill = Genus)) +
  geom_bar(position= "stack", stat = "identity") +
  scale_fill_manual(values = color_mapping) +
  theme_minimal() +
  labs(title = "barplot inhouse_wetsus_2023 mock communities", x = "Sample", y = "Abundantie (%)", fill = "Genus")

ggsave("figures/bar_plot_inhouse_wetsus_2023.pdf", plot = bar_plot_inhouse_wetsus_2023, width = 6, height = 4)
ggsave("figures/bar_plot_inhouse_wetsus_2023.jpg", plot = bar_plot_inhouse_wetsus_2023, width = 6, height = 4)

bar_plot_inhouse_wetsus_2023

Genus_abundance_inhouse_wetsus_2023 = 
  mock_only_Inhouse_wetsus_2023_samples_2 %>% 
  group_by(Sample, Genus) %>%
  summarize(total_abundance = sum(abund))

# Zymo_log10
mock_only_zymo_log10_samples =
Zymo_log10_studies %>%
  lapply(function(df) {
    df %>% 
  filter(Sample_mock == "mock") %>%
  select(OTU, Sample, everything()) %>% 
  mutate(Sample = if_else(str_sub(Sample, -1)== "C", str_replace(Sample, "C$", ""), Sample)) %>% 
  group_by(across(-c(SampleID, Abundance, read_count))) %>% 
  summarise(mean_abundance = mean(Abundance), 
            mean_read_count = mean(read_count), 
            mean_dna_conc = mean(DNA_Concentration), .groups = "drop") %>% 
  distinct() %>% 
  group_by(Sample, Genus) %>%   
  summarise(abund = sum(mean_abundance),
            readcount = sum(mean_read_count),
            dnaconc = mean(mean_dna_conc),
            .groups = "drop") %>% 
  arrange(-abund)
  }) %>% 
  bind_rows()

Zymo_mock =
  c("Listeria", "Pseudomonas", "Bacillus", "Saccharomyces", "Escherichia-Shigella", "Salmonella", "Lactobacillus", "Enterococcus", "Cryptococcus", "Staphylococcus")

mock_only_zymo_log10_samples_2 = 
  mock_only_zymo_log10_samples %>% 
  filter(!Sample %in% c("MCL1", "MCL2")) %>% 
  mutate(Genus = ifelse(Genus %in% Zymo_mock, Genus, "Other genus")) %>% 
  mutate(Genus = factor(Genus, levels = c(setdiff(unique(Genus), "Other genus"), "Other genus")))

bar_plot_zymo_log10 =
  ggplot(mock_only_zymo_log10_samples_2, aes(x = Sample , y = abund, fill = Genus)) +
  geom_bar(position= "stack", stat = "identity") +
  scale_fill_manual(values = color_mapping) +
  theme_minimal() +
  labs(title = "barplot zyno_log10 mock communities", x = "Sample", y = "Abundantie (%)", fill = "Genus")

ggsave("figures/bar_plot_zymo_log10.pdf", plot = bar_plot_zymo_log10, width = 6, height = 4)
ggsave("figures/bar_plot_zymo_log10.jpg", plot = bar_plot_zymo_log10, width = 6, height = 4)

bar_plot_zymo_log10

Genus_abundance_zymo_log10 = 
  mock_only_zymo_log10_samples_2 %>% 
  group_by(Sample, Genus) %>%
  summarize(total_abundance = sum(abund))

# Zymo_equil
mock_only_zymo_equil_samples =
Zymo_equil_studies %>%
  lapply(function(df) {
    df %>% 
  filter(Sample_mock == "mock") %>%
  select(OTU, Sample, everything()) %>% 
  mutate(Sample = if_else(str_sub(Sample, -1)== "C", str_replace(Sample, "C$", ""), Sample)) %>% 
  group_by(across(-c(SampleID, Abundance, read_count))) %>% 
  summarise(mean_abundance = mean(Abundance), 
            mean_read_count = mean(read_count), 
            mean_dna_conc = mean(DNA_Concentration), .groups = "drop") %>% 
  distinct() %>% 
  group_by(Sample, Genus) %>%   
  summarise(abund = sum(mean_abundance),
            readcount = sum(mean_read_count),
            dnaconc = mean(mean_dna_conc),
            .groups = "drop") %>% 
  arrange(-abund)
  }) %>% 
  bind_rows()

Zymo_mock =
  c("Listeria", "Pseudomonas", "Bacillus", "Saccharomyces", "Escherichia-Shigella", "Salmonella", "Lactobacillus", "Enterococcus", "Cryptococcus", "Staphylococcus")

mock_only_zymo_equil_samples_2 = 
  mock_only_zymo_equil_samples %>% 
  filter(!Sample %in% c("MCL1", "MCL2")) %>% 
  mutate(Genus = ifelse(Genus %in% Zymo_mock, Genus, "Other genus")) %>% 
  mutate(Genus = factor(Genus, levels = c(setdiff(unique(Genus), "Other genus"), "Other genus")))

bar_plot_zymo_equil =
  ggplot(mock_only_zymo_equil_samples_2, aes(x = Sample , y = abund, fill = Genus)) +
  geom_bar(position= "stack", stat = "identity") +
  scale_fill_manual(values = color_mapping) +
  theme_minimal() +
  labs(title = "barplot zymo_equil mock communities", x = "Sample", y = "Abundantie (%)", fill = "Genus")

ggsave("figures/bar_plot_zymo_equil.pdf", plot = bar_plot_zymo_equil, width = 6, height = 4)
ggsave("figures/bar_plot_zymo_equil.jpg", plot = bar_plot_zymo_equil, width = 6, height = 4)

bar_plot_zymo_equil

Genus_abundance_zymo_equil = 
  mock_only_zymo_equil_samples_2 %>% 
  group_by(Sample, Genus) %>%
  summarize(total_abundance = sum(abund))
```

```{r view genera in the mock}
# view all genera in mock
mock_only_Inhouse_wetsus_2022_samples %>% 
  filter(abund > 0) %>% 
  select(Genus) %>%
  unique %>%
  view()

mock_only_Inhouse_wetsus_2023_samples %>% 
  filter(abund > 0) %>% 
  select(Genus) %>%
  unique %>%
  view()

mock_only_zymo_log10_samples %>% 
  filter(abund > 0) %>% 
  select(Genus) %>%
  unique %>%
  view()

mock_only_zymo_equil_samples %>% 
  filter(abund > 0) %>% 
  select(Genus) %>%
  unique %>%
  view()
```

```{r subset mock communities, eval=TRUE, echo=TRUE, include=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
# Table of mock composition
Zymo_log10 =
  tibble(Genus = c("Listeria",
                   "Pseudomonas",
                   "Bacillus",
                   "Saccharomyces",
                   "Escherichia-Shigella",
                   "Salmonella",
                   "Lactobacillus",
                   "Enterococcus",
                   "Cryptococcus",
                   "Staphylococcus"),
         zymo_abund = c(
                   95.9,
                   2.8,
                   1.2,
                   0,
                   0.069,
                   0.07,
                   0.012,
                   0.00067,
                   0,
                   0.0001))

Zymo_equil =
  tibble(Genus = c("Pseudomonas", 
                   "Escherichia-Shigella", 
                   "Salmonella", 
                   "Lactobacillus", 
                   "Enterococcus", 
                   "Staphylococcus", 
                   "Listeria", 
                   "Bacillus", 
                   "Saccharomyces", 
                   "Cryptococcus"),
         zymo_abund = c(
                   4.2,
                   10.1,
                   10.4,
                   18.4,
                   9.9,
                   15.5,
                   14.1,
                   17.4,
                   0,
                   0)) 

Inhouse2022 =
  tibble(Genus = c("Serratia",
                   "Massilia",
                   "Brevibacillus",
                   "Bacillus",
                   "Weizmannia",
                   "Lysinibacillus",
                   "Peribacillus",
                   "Bordetella"),
         Inhouse2022_abund = c(
                   50,
                   25,
                   12.5,
                   6.25,
                   3.13,
                   1.56,
                   0.78,
                   0.39))


Inhouse2022_correct =
  tibble(Genus = c("Brevibacillus",
                   "Bacillus",
                   "Lysinibacillus",
                   "Bordetella"),
         Inhouse2022_abund = c(
                   55.17,
                   36.21,
                   6.90,
                   1.72))

Inhouse2023 =
  tibble(Genus = c("Brevibacillus",
                   "Bacillus",
                   "Lysinibacillus",
                   "Sphingobium",
                   "Streptomyces",
                   "Burkholderia-Caballeronia-Paraburkholderia"),
         Inhouse2023_abund = c(
                   50.78,
                   31.73,
                   12.69,
                   3.18,
                   0.79,
                   0.40))

Inhouse_PRJNA648321 =
  tibble(Genus = c("Pseudomonas",
                   "Escherichia",
                   "Agrobacterium",
                   "Salmonella",
                   "Lactobacillus",
                   "Enterococcus",
                   "Staphylococcus",
                   "Listeria",
                   "Bacillus"),
         Inhouse_PRJNA648321_abund = c(
                  9.48,
                  13.08,
                  3.32,
                  34.12,
                  7.30,
                  14.22,
                  5.50,
                  10.43,
                  2.56))
# 
# Inhouse_PRJEB36253 =
#   tibble(Genus = c(""),
#          Inhouse_PRJEB36253_abund = c(
#            
#          ))
```

```{r abudance theoretical vs measured, eval=TRUE, echo=TRUE, include=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
# Theoretical vs measured abundance 

# inhouse wetsus 2022
table_measured_vs_theoretical_inhouse_wetsus_2022 = 
  mock_only_Inhouse_wetsus_2022_samples %>% 
  filter(!Sample %in% c("MCZ", "MC23")) %>% 
  group_by(Genus) %>% 
  summarise(mean_abundance_inhouse_wetsus_2022 = mean(abund)) %>% 
  select(Genus, mean_abundance_inhouse_wetsus_2022) %>% 
  inner_join(Inhouse2022_correct, by = "Genus")

plot_measured_vs_theoretical_inhouse_wetsus_2022 =
  ggplot(table_measured_vs_theoretical_inhouse_wetsus_2022, aes(x = Inhouse2022_abund, 
                                                                y = mean_abundance_inhouse_wetsus_2022)) +
  geom_point(size = 3) +
  geom_text_repel(aes(label = Genus), box.padding = 0.5, hjust = 0.5, vjust = 1.0) +
  
  #geom_text(aes(label = Genus), hjust = 0.5, vjust = -1.0, check_overlap = TRUE) +
  labs(title = "Inhouse wetsus 2022",
       x = "Theoretische Abundantie",
       y = "Gemeten Abundantie") +
  theme_minimal() +
  theme(legend.position = "none") +
  geom_abline(intercept = 0, slope = 1) +
  ylim(0, NA) 

ggsave("figures/plot_measured_vs_theoretical_inhouse_wetsus_2022.pdf", plot = plot_measured_vs_theoretical_inhouse_wetsus_2022, width = 6, height = 4)
ggsave("figures/plot_measured_vs_theoretical_inhouse_wetsus_2022.jpg", plot = plot_measured_vs_theoretical_inhouse_wetsus_2022, width = 6, height = 4)

plot_measured_vs_theoretical_inhouse_wetsus_2022

abundance_difference_inhouse_wetsus_2022 =
  table_measured_vs_theoretical_inhouse_wetsus_2022$mean_abundance_inhouse_wetsus_2022 -     table_measured_vs_theoretical_inhouse_wetsus_2022$Inhouse2022_abund

#t_test_result <- t.test(abundance_difference_inhouse_wetsus_2022)

# inhouse wetsus 2023
table_measured_vs_theoretical_inhouse_wetsus_2023 = 
  mock_only_Inhouse_wetsus_2023_samples %>% 
  filter(Sample != "MC22") %>% 
  group_by(Genus) %>% 
  summarise(mean_abundance_inhouse_wetsus_2023 = mean(abund)) %>% 
  select(Genus, mean_abundance_inhouse_wetsus_2023) %>% 
  inner_join(Inhouse2023, by = "Genus")

plot_measured_vs_theoretical_inhouse_wetsus_2023 =
  ggplot(table_measured_vs_theoretical_inhouse_wetsus_2023, aes(x = Inhouse2023_abund, 
                                                              y = mean_abundance_inhouse_wetsus_2023)) +
  geom_point(size = 3) +
  #geom_text_repel(aes(label = Genus), box.padding = 0.5, hjust = 0.5, vjust = 1.0) +
  
  #geom_text(aes(label = Genus), hjust = 0.5, vjust = -1.0, check_overlap = TRUE) +
  labs(title = "Inhouse wetsus 2023",
       x = "Theoretische Abundantie",
       y = "Gemeten Abundantie") +
  theme_minimal() +
  theme(legend.position = "none") +
  geom_abline(intercept = 0, slope = 1) +
  ylim(0, NA) 

ggsave("figures/plot_measured_vs_theoretical_inhouse_wetsus_2023.pdf", plot = plot_measured_vs_theoretical_inhouse_wetsus_2023, width = 6, height = 4)
ggsave("figures/plot_measured_vs_theoretical_inhouse_wetsus_2023.jpg", plot = plot_measured_vs_theoretical_inhouse_wetsus_2023, width = 6, height = 4)

plot_measured_vs_theoretical_inhouse_wetsus_2023

abundance_difference_inhouse_wetsus_2023 =
  table_measured_vs_theoretical_inhouse_wetsus_2023$mean_abundance_inhouse_wetsus_2023 -     table_measured_vs_theoretical_inhouse_wetsus_2023$Inhouse2023_abund

# zymo_log10
table_measured_vs_theoretical_zymo_log10 = 
  mock_only_zymo_log10_samples %>%
  group_by(Genus) %>% 
  summarise(mean_abundance_zymo_log10 = mean(abund)) %>% 
  select(Genus, mean_abundance_zymo_log10) %>% 
  inner_join(Zymo_log10, by = "Genus")

plot_measured_vs_theoretical_zumo_log10 =
  ggplot(table_measured_vs_theoretical_zymo_log10, aes(x = zymo_abund, 
                                                     y = mean_abundance_zymo_log10+0.00001)) +
  geom_point(size = 3) +
  scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),
                labels = scales::trans_format("log10", scales::math_format(10^.x)),
                limits = c(0.00001, 100)) +
  scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),
                labels = scales::trans_format("log10", scales::math_format(10^.x)),
                limits = c(0.00001, 100)) +
  #geom_text_repel(aes(label = Genus), box.padding = 0.5, hjust = 0.5, vjust = 1.0) +
  
  #geom_text(aes(label = Genus), hjust = 0.5, vjust = -1.0, check_overlap = TRUE) +
  labs(title = "Zymo_log10",
       x = "Theoretische Abundantie",
       y = "Gemeten Abundantie") +
  theme_minimal() +
  theme(legend.position = "none") +
  geom_abline(intercept = 0, slope = 1) +
  geom_text_repel(aes(label = Genus), size = 3,  box.padding = 0.5, hjust = 0.5, vjust = 1.0) 

ggsave("figures/plot_measured_vs_theoretical_zumo_log10.pdf", plot = plot_measured_vs_theoretical_zumo_log10, width = 6, height = 4)
ggsave("figures/plot_measured_vs_theoretical_zumo_log10.jpg", plot = plot_measured_vs_theoretical_zumo_log10, width = 6, height = 4)

plot_measured_vs_theoretical_zumo_log10

abundance_difference_zymo_log10 =
  table_measured_vs_theoretical_zymo_log10$mean_abundance_zymo_log10 -     table_measured_vs_theoretical_zymo_log10$zymo_abund

# zymo_equil
table_measured_vs_theoretical_zymo_equil = 
  mock_only_zymo_equil_samples %>% 
  filter(!Sample %in% c("MCL1", "MCL2")) %>% 
  group_by(Genus) %>% 
  summarise(mean_abundance_zymo_equil = mean(abund)) %>% 
  select(Genus, mean_abundance_zymo_equil) %>% 
  inner_join(Zymo_equil, by = "Genus")

plot_measured_vs_theoretical_zymo_equl =
  ggplot(table_measured_vs_theoretical_zymo_equil, aes(x = zymo_abund, 
                                                     y = mean_abundance_zymo_equil)) +
  geom_point(size = 3) +
  geom_text_repel(aes(label = Genus), size = 3, box.padding = 0.5, hjust = 0.5, vjust = 1.0) +
  
  #geom_text(aes(label = Genus), hjust = 0.5, vjust = -1.0, check_overlap = TRUE) +
  labs(title = "Zymo_equil",
       x = "Theoretische Abundantie",
       y = "Gemeten Abundantie") +
  theme_minimal() +
  theme(legend.position = "none") +
  geom_abline(intercept = 0, slope = 1) +
  ylim(0, NA) 

ggsave("figures/plot_measured_vs_theoretical_zymo_equl.pdf", plot = plot_measured_vs_theoretical_zymo_equl, width = 6, height = 4)
ggsave("figures/plot_measured_vs_theoretical_zymo_equl.jpg", plot = plot_measured_vs_theoretical_zymo_equl, width = 6, height = 4)

plot_measured_vs_theoretical_zymo_equl

abundance_difference_zymo_equil =
  table_measured_vs_theoretical_zymo_equil$mean_abundance_zymo_equil -     table_measured_vs_theoretical_zymo_equil$zymo_abund

```

```{r unique mock, eval=TRUE, echo=TRUE, include=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
# mock samples that are not include in de calculation of mean, sd and CV
all_mock <- c("MC22", "MC23", "MCL1", "MCL2", "MCZ", "OSOJ.13", "OSOJ.1.13", "OSOJ.2.5", "OSOJ.2.5", "SHSU.5", "LUO.89", "YXIN32")

# collection of mock species included in mock
unique_mock_inhouse_wetsus_2022_species =  
  tibble(Genus = c("Serratia","Massilia","Brevibacillus","Bacillus","Weizmannia","Lysinibacillus","Peribacillus","Bordetella"  ,"Sphingobium","Streptomyces","Burkholderia","Burkholderia-Caballeronia-Paraburkholderia","Genus of Bacilli"))

unique_mock_inhouse_wetsus_2023_species =
  tibble(Genus = c("Brevibacillus","Weizmannia","Lysinibacillus","Bacillus","Sphingobium","Serratia","Streptomyces","Burkholderia","Burkholderia-Caballeronia-Paraburkholderia","Novosphingobium","Genus of Enterobacteriaceae"))

unique_mock_zymo_log10_species = 
  tibble(Genus = c("Listeria","Pseudomonas","Bacillus","Saccharomyces","Escherichia-Shigella","Salmonella","Lactobacillus","Enterococcus","Cryptococcus","Staphylococcus","Genus of Enterococcaceae"))

unique_mock_zymo_equil_species = 
  tibble(Genus = c("Listeria","Pseudomonas","Bacillus","Saccharomyces","Escherichia-Shigella","Salmonella","Lactobacillus","Enterococcus","Cryptococcus","Staphylococcus"))
```

```{r DNA concentration sample / DNA concentration mock (ratio) (sampels), eval=TRUE, echo=TRUE, include=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
# Divide the DNA concentration of the mock by the DNA concentration of the sample

# inhouse_wetsus_2022
Inhouse_wetsus_2022_studies_samples_ratio <-
  Inhouse_wetsus_2022_studies %>% 
  lapply(function(df) {
    mock_dna_concentration_inhouse_wetsus_2022 =
      df %>% 
      filter(Sample_mock == "mock") %>% 
      filter(!Sample %in% c("MCZ", "MC23")) %>% 
      summarise(mean_mock_inhouse_wetsus_2022_dna_conc = mean(DNA_Concentration, na.rm = TRUE)) %>% 
      pull(mean_mock_inhouse_wetsus_2022_dna_conc)
    
      df %>%
      filter(Sample_mock != "blank") %>% 
      select(OTU, Sample, everything()) %>% 
      mutate(Sample = if_else(str_sub(Sample, -1)== "C", str_replace(Sample, "C$", ""), Sample)) %>% 
      group_by(across(-c(SampleID, Abundance, read_count))) %>% 
      summarise(mean_abundance = mean(Abundance), 
            mean_read_count = mean(read_count), 
            mean_dna_conc = mean(DNA_Concentration) / mock_dna_concentration_inhouse_wetsus_2022,
            .groups = "drop") %>% 
      distinct() %>% 
      group_by(Sample, Genus) %>%   
      summarise(abund = sum(mean_abundance),
            readcount = sum(mean_read_count),
            dnaconc = mean(mean_dna_conc),
            .groups = "drop") %>% 
      arrange(-abund)
    }) %>% 
  bind_rows()

# inhouse_wetsus_2023
Inhouse_wetsus_2023_studies_samples_ratio <-
  Inhouse_wetsus_2023_studies %>% 
  lapply(function(df) {
    mock_dna_concentration_inhouse_wetsus_2023 =
      df %>% 
      filter(Sample_mock == "mock") %>% 
      filter(!Sample %in% c("MCZ", "MC22")) %>%  
      summarise(mean_mock_inhouse_wetsus_2023_dna_conc = mean(DNA_Concentration, na.rm = TRUE)) %>% 
      pull(mean_mock_inhouse_wetsus_2023_dna_conc)
    
      df %>%
      filter(Sample_mock != "blank") %>% 
      select(OTU, Sample, everything()) %>% 
      mutate(Sample = if_else(str_sub(Sample, -1)== "C", str_replace(Sample, "C$", ""), Sample)) %>% 
      group_by(across(-c(SampleID, Abundance, read_count))) %>% 
      summarise(mean_abundance = mean(Abundance), 
            mean_read_count = mean(read_count), 
            mean_dna_conc = mean(DNA_Concentration) / mock_dna_concentration_inhouse_wetsus_2023,
            .groups = "drop") %>% 
      distinct() %>% 
      group_by(Sample, Genus) %>%   
      summarise(abund = sum(mean_abundance),
            readcount = sum(mean_read_count),
            dnaconc = mean(mean_dna_conc),
            .groups = "drop") %>% 
      arrange(-abund)
    }) %>% 
  bind_rows()

# zymo_log10
Zymo_log10_studies_samples_ratio <-
  Zymo_log10_studies %>% 
  lapply(function(df) {
    mock_dna_concentration_zymo_log10 =
      df %>% 
      filter(Sample_mock == "mock") %>% 
      summarise(mean_mock_zymo_log10_dna_conc = mean(DNA_Concentration, na.rm = TRUE)) %>% 
      pull(mean_mock_zymo_log10_dna_conc)
    
      df %>%
      filter(Sample_mock != "blank") %>% 
      select(OTU, Sample, everything()) %>% 
      mutate(Sample = if_else(str_sub(Sample, -1)== "C", str_replace(Sample, "C$", ""), Sample)) %>% 
      group_by(across(-c(SampleID, Abundance, read_count))) %>% 
      summarise(mean_abundance = mean(Abundance), 
            mean_read_count = mean(read_count), 
            mean_dna_conc = mean(DNA_Concentration) / mock_dna_concentration_zymo_log10,
            .groups = "drop") %>% 
      distinct() %>% 
      group_by(Sample, Genus) %>%   
      summarise(abund = sum(mean_abundance),
            readcount = sum(mean_read_count),
            dnaconc = mean(mean_dna_conc),
            .groups = "drop") %>% 
      arrange(-abund)
    }) %>% 
  bind_rows()

# zymo_equil
Zymo_equil_studies_samples_ratio <-
  Zymo_equil_studies %>% 
  lapply(function(df) {
    mock_dna_concentration_zymo_equil =
      df %>% 
      filter(Sample_mock == "mock",  !Sample %in% c("MCL1", "MCL2")) %>% 
      summarise(mean_mock_zymo_equil_dna_conc = mean(DNA_Concentration, na.rm = TRUE)) %>% 
      pull(mean_mock_zymo_equil_dna_conc)
    
      df %>%
      filter(Sample_mock != "blank") %>% 
      select(OTU, Sample, everything()) %>% 
      mutate(Sample = if_else(str_sub(Sample, -1)== "C", str_replace(Sample, "C$", ""), Sample)) %>% 
      group_by(across(-c(SampleID, Abundance, read_count))) %>% 
      summarise(mean_abundance = mean(Abundance), 
            mean_read_count = mean(read_count), 
            mean_dna_conc = mean(DNA_Concentration) / mock_dna_concentration_zymo_equil,
            .groups = "drop") %>% 
      distinct() %>% 
      group_by(Sample, Genus) %>%   
      summarise(abund = sum(mean_abundance),
            readcount = sum(mean_read_count),
            dnaconc = mean(mean_dna_conc),
            .groups = "drop") %>% 
      arrange(-abund)
    }) %>% 
  bind_rows()
```

```{r tabel maken voor plot sampel / mock (samples), eval=TRUE, echo=TRUE, include=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
# calculate mean, sd and cv across all samples for every Genus
table_Inhouse_wetsus_2022_samples_ratio = 
  Inhouse_wetsus_2022_studies_samples_ratio %>% 
  select(Genus, Sample, abund) %>% 
  pivot_wider(names_from = Sample, values_from = abund, values_fill = 0) %>%
  rowwise() %>%   
  mutate(mean = mean(c_across(where(is.numeric) & !matches(all_mock))),
         sd = sd(c_across(where(is.numeric) & !matches(all_mock))),
         CV = sd/mean*100) %>% 
  arrange(-mean) %>% 
  ungroup()

table_Inhouse_wetsus_2023_samples_ratio = 
  Inhouse_wetsus_2023_studies_samples_ratio %>% 
  select(Genus, Sample, abund) %>% 
  pivot_wider(names_from = Sample, values_from = abund, values_fill = 0) %>%
  rowwise() %>%   
  mutate(mean = mean(c_across(where(is.numeric) & !matches(all_mock))),
         sd = sd(c_across(where(is.numeric) & !matches(all_mock))),
         CV = sd/mean*100) %>% 
  arrange(-mean) %>% 
  ungroup()

table_Zymo_log10_samples_ratio = 
  Zymo_log10_studies_samples_ratio %>% 
  select(Genus, Sample, abund) %>% 
  pivot_wider(names_from = Sample, values_from = abund, values_fill = 0) %>%
  rowwise() %>%   
  mutate(mean = mean(c_across(where(is.numeric) & !matches(all_mock))),
         sd = sd(c_across(where(is.numeric) & !matches(all_mock))),
         CV = sd/mean*100) %>% 
  arrange(-mean) %>% 
  ungroup()

table_Zymo_equil_samples_ratio = 
  Zymo_equil_studies_samples_ratio %>% 
  select(Genus, Sample, abund) %>% 
  pivot_wider(names_from = Sample, values_from = abund, values_fill = 0) %>%
  rowwise() %>%   
  mutate(mean = mean(c_across(where(is.numeric) & !matches(all_mock))),
         sd = sd(c_across(where(is.numeric) & !matches(all_mock))),
         CV = sd/mean*100) %>% 
  arrange(-mean) %>% 
  ungroup()

# remove mean, sd, cv from table and also remove mock sampels
# plotting results 
table2_inhouse_wetsus_2022_samples_ratio =
  table_Inhouse_wetsus_2022_samples_ratio %>% 
  filter(Genus %in% unique_mock_inhouse_wetsus_2022_species$Genus) %>% 
  select(-mean, -sd, -CV) %>% 
  pivot_longer(cols = -c(Genus), names_to = "Sample", values_to = "abund") %>% 
  left_join(., Inhouse_wetsus_2022_studies_samples_ratio %>% 
              select(Sample, dnaconc) %>% 
              distinct(), by = "Sample") %>% 
   filter(!Sample %in% mock_names_inhouse_wetsus_2022$Sample)

table2_inhouse_wetsus_2023_samples_ratio =
table_Inhouse_wetsus_2023_samples_ratio %>% 
  filter(Genus %in% unique_mock_inhouse_wetsus_2023_species$Genus) %>%
  select(-mean, -sd, -CV) %>% 
  pivot_longer(cols = -c(Genus), names_to = "Sample", values_to = "abund") %>% 
  left_join(., Inhouse_wetsus_2023_studies_samples_ratio %>% 
              select(Sample, dnaconc) %>% 
              distinct(), by = "Sample") %>% 
  filter(!Sample %in% mock_names_inhouse_wetsus_2023$Sample)

table2_zymo_log10_samples_ratio =
table_Zymo_log10_samples_ratio %>% 
  filter(Genus %in% unique_mock_zymo_log10_species$Genus) %>%
  select(-mean, -sd, -CV) %>% 
  pivot_longer(cols = -c(Genus), names_to = "Sample", values_to = "abund") %>% 
  left_join(., Zymo_log10_studies_samples_ratio %>% 
              select(Sample, dnaconc) %>% 
              distinct(), by = "Sample") %>% 
  filter(!Sample %in% mock_names_zymo_log10$Sample)

table2_zymo_equil_samples_ratio =
table_Zymo_equil_samples_ratio %>% 
  filter(Genus %in% unique_mock_zymo_equil_species$Genus) %>%
  select(-mean, -sd, -CV) %>% 
  pivot_longer(cols = -c(Genus), names_to = "Sample", values_to = "abund") %>% 
  left_join(., Zymo_equil_studies_samples_ratio %>% 
              select(Sample, dnaconc) %>% 
              distinct(), by = "Sample") %>%
  filter(!Sample %in% mock_names_zymo_equil$Sample)
```

```{r grafiek plotten voor sample / mock (sampels), eval=TRUE, echo=TRUE, include=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
# plot inhouse_wetsus_2022
plot_inhouse_wetsus_2022_samples_ratio =
  ggplot(table2_inhouse_wetsus_2022_samples_ratio, aes(x = dnaconc, y = abund, title)) + 
  geom_point(aes(color = Genus), position = position_dodge(width = 0.5)) + 
  facet_wrap(~Genus) +
  scale_y_continuous(transform = "log2") +
  geom_smooth(method = "lm", se = F, color = "grey50") +
  theme(axis.text.x = element_text(size = 8)) +
  labs(x = 'Ratio in DNA Concentratie (ng/l)', y = 'Abundantie (%)', title = 'plot_inhouse_wetsus_2022_samples_ratio')

ggsave("figures/plot_inhouse_wetsus_2022_samples_ratio.pdf", plot = plot_inhouse_wetsus_2022_samples_ratio, width = 6, height = 4)
ggsave("figures/plot_inhouse_wetsus_2022_sampels_ratio.jpg", plot = plot_inhouse_wetsus_2022_samples_ratio, width = 6, height = 4)

plot_inhouse_wetsus_2022_samples_ratio

# Plot inhouse_wetsus_2023
plot_inhouse_wetsus_2023_samples_ratio =
ggplot(table2_inhouse_wetsus_2023_samples_ratio, aes(x = dnaconc, y = abund)) + 
  geom_point(aes(color = Genus), position = position_dodge(width = 0.5)) + 
  facet_wrap(~Genus) +
  scale_y_continuous(transform = "log2") +
  geom_smooth(method = "lm", se = F, color = "grey50") +
  theme(axis.text.x = element_text(size = 8)) +
  labs(x = 'Ratio in DNA Concentratie (ng/l)', y = 'Abundantie (%)', title = 'plot_inhouse_wetsus_2023_samples_ratio')

ggsave("figures/plot_inhouse_wetsus_2023_samples_ratio.pdf", plot = plot_inhouse_wetsus_2023_samples_ratio, width = 6, height = 4)
ggsave("figures/plot_inhouse_wetsus_2023_samples_ratio.jpg", plot = plot_inhouse_wetsus_2023_samples_ratio, width = 6, height = 4)

plot_inhouse_wetsus_2023_samples_ratio

# plot zymo log10
plot_zymo_log10_samples_ratio =
ggplot(table2_zymo_log10_samples_ratio, aes(x = dnaconc, y = abund)) + 
  geom_point(aes(color = Genus), position = position_dodge(width = 0.5)) + 
  facet_wrap(~Genus) +
  scale_y_continuous(transform = "log2") +
  geom_smooth(method = "lm", se = F, color = "grey50") +
  theme(axis.text.x = element_text(size = 8)) +
  labs(x = 'Ratio in DNA Concentratie (ng/l)', y = 'Abundantie (%)', title = 'plot_zymo_log10_samples_ratio')

ggsave("figures/plot_zymo_log10_samples_ratio.pdf", plot = plot_zymo_log10_samples_ratio, width = 6, height = 4)
ggsave("figures/plot_zymo_log10_samples_ratio.jpg", plot = plot_zymo_log10_samples_ratio, width = 6, height = 4)

plot_zymo_log10_samples_ratio

# plot zymo equil 
plot_zymo_equil_samples_ratio =
ggplot(table2_zymo_equil_samples_ratio, aes(x = dnaconc, y = abund)) + 
  geom_point(aes(color = Genus), position = position_dodge(width = 0.5)) + 
  facet_wrap(~Genus) +
  scale_y_continuous(transform = "log2") +
  geom_smooth(method = "lm", se = F, color = "grey50") +
  theme(axis.text.x = element_text(size = 8)) +
  labs(x = 'Ratio in DNA Concentratie (ng/l)', y = 'Abundantie (%)', title = 'plot_zymo_equil_samples_ratio')

ggsave("figures/plot_zymo_equil_samples_ratio.pdf", plot = plot_zymo_equil_samples_ratio, width = 6, height = 4)
ggsave("figures/plot_zymo_equil_samples_ratio.jpg", plot = plot_zymo_equil_samples_ratio, width = 6, height = 4)

plot_zymo_equil_samples_ratio
```

```{r statistiek (sampels)}
# statistic 

table2_inhouse_wetsus_2022_samples_ratio %>% 
  mutate(log2_abund = log2(abund+0.0000001)) %>% 
  with(lmerTest::lmer(log2_abund ~ dnaconc + (1|Genus))) %>% 
  anova

table2_inhouse_wetsus_2023_samples_ratio %>% 
  mutate(log2_abund = log2(abund+0.0000001)) %>% 
  with(lmerTest::lmer(log2_abund ~ dnaconc + (1|Genus))) %>% 
  anova

table2_zymo_log10_samples_ratio %>% 
  mutate(log2_abund = log2(abund+0.0000001)) %>% 
  with(lmerTest::lmer(log2_abund ~ dnaconc + (1|Genus))) %>% 
  anova

table2_zymo_equil_samples_ratio %>% 
  mutate(log2_abund = log2(abund+0.0000001)) %>% 
  with(lmerTest::lmer(log2_abund ~ dnaconc + (1|Genus))) %>% 
  anova

```

```{r DNA cocnetratie sample / DNA cocnetratie mock (ratio) (MOCK), eval=TRUE, echo=TRUE, include=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
# Divide the DNA concentration of the mock by the DNA concentration of the sample 
# inhouse_wetsus_2022
Inhouse_wetsus_2022_studies_mock_ratio <-
  Inhouse_wetsus_2022_studies %>% 
  lapply(function(df) {
    mock_dna_concentration_inhouse_wetsus_2022 =
      df %>% 
      filter(Sample_mock == "mock") %>% 
      filter(!Sample %in% c("MCZ", "MC23")) %>%  
      summarise(mean_mock_inhouse_wetsus_2022_dna_conc = mean(DNA_Concentration, na.rm = TRUE)) %>% 
      pull(mean_mock_inhouse_wetsus_2022_dna_conc)
    
      df %>%
      filter(!(Sample_mock %in% c("blank"))) %>% 
      select(OTU, Sample, everything()) %>% 
      mutate(Sample = if_else(str_sub(Sample, -1)== "C", str_replace(Sample, "C$", ""), Sample)) %>% 
      group_by(across(-c(SampleID, Abundance, read_count))) %>% 
      summarise(mean_abundance = mean(Abundance), 
            mean_read_count = mean(read_count), 
            mean_dna_conc = mean(DNA_Concentration) / mock_dna_concentration_inhouse_wetsus_2022,
            .groups = "drop") %>% 
      distinct() %>% 
      group_by(Sample, Genus) %>%   
      summarise(abund = sum(mean_abundance),
            readcount = sum(mean_read_count),
            dnaconc = mean(mean_dna_conc),
            .groups = "drop") %>% 
      arrange(-abund)
    }) %>% 
  bind_rows()

# inhouse_wetsus_2023
Inhouse_wetsus_2023_studies_mock_ratio <-
  Inhouse_wetsus_2023_studies %>% 
  lapply(function(df) {
    mock_dna_concentration_inhouse_wetsus_2023 =
      df %>% 
      filter(Sample_mock == "mock") %>% 
      filter(!Sample %in% c("MCZ", "MC22")) %>%  
      summarise(mean_mock_inhouse_wetsus_2023_dna_conc = mean(DNA_Concentration, na.rm = TRUE)) %>% 
      pull(mean_mock_inhouse_wetsus_2023_dna_conc)
    
      df %>%
      filter(Sample_mock != "blank") %>% 
      select(OTU, Sample, everything()) %>% 
      mutate(Sample = if_else(str_sub(Sample, -1)== "C", str_replace(Sample, "C$", ""), Sample)) %>% 
      group_by(across(-c(SampleID, Abundance, read_count))) %>% 
      summarise(mean_abundance = mean(Abundance), 
            mean_read_count = mean(read_count), 
            mean_dna_conc = mean(DNA_Concentration) / mock_dna_concentration_inhouse_wetsus_2023,
            .groups = "drop") %>% 
      distinct() %>% 
      group_by(Sample, Genus) %>%   
      summarise(abund = sum(mean_abundance),
            readcount = sum(mean_read_count),
            dnaconc = mean(mean_dna_conc),
            .groups = "drop") %>% 
      arrange(-abund)
    }) %>% 
  bind_rows()

# zymo_log10
Zymo_log10_studies_mock_ratio <-
  Zymo_log10_studies %>% 
  lapply(function(df) {
    mock_dna_concentration_zymo_log10 =
      df %>% 
      filter(Sample_mock == "mock",  Sample != "MCZ") %>% 
      summarise(mean_mock_zymo_log10_dna_conc = mean(DNA_Concentration, na.rm = TRUE)) %>% 
      pull(mean_mock_zymo_log10_dna_conc)
    
      df %>%
      filter(Sample_mock != "blank") %>% 
      select(OTU, Sample, everything()) %>% 
      mutate(Sample = if_else(str_sub(Sample, -1)== "C", str_replace(Sample, "C$", ""), Sample)) %>% 
      group_by(across(-c(SampleID, Abundance, read_count))) %>% 
      summarise(mean_abundance = mean(Abundance), 
            mean_read_count = mean(read_count), 
            mean_dna_conc = mean(DNA_Concentration) / mock_dna_concentration_zymo_log10,
            .groups = "drop") %>% 
      distinct() %>% 
      group_by(Sample, Genus) %>%   
      summarise(abund = sum(mean_abundance),
            readcount = sum(mean_read_count),
            dnaconc = mean(mean_dna_conc),
            .groups = "drop") %>% 
      arrange(-abund)
    }) %>% 
  bind_rows()

# zymo_equil
Zymo_equil_studies_mock_ratio <-
  Zymo_equil_studies %>% 
  lapply(function(df) {
    mock_dna_concentration_zymo_equil =
      df %>% 
      filter(Sample_mock == "mock",  !Sample %in% c("MCL1", "MCL2")) %>% 
      summarise(mean_mock_zymo_equil_dna_conc = mean(DNA_Concentration, na.rm = TRUE)) %>% 
      pull(mean_mock_zymo_equil_dna_conc)
    
      df %>%
      filter(Sample_mock != "blank") %>% 
      select(OTU, Sample, everything()) %>% 
      mutate(Sample = if_else(str_sub(Sample, -1)== "C", str_replace(Sample, "C$", ""), Sample)) %>% 
      group_by(across(-c(SampleID, Abundance, read_count))) %>% 
      summarise(mean_abundance = mean(Abundance), 
            mean_read_count = mean(read_count), 
            mean_dna_conc = mean(DNA_Concentration) / mock_dna_concentration_zymo_equil,
            .groups = "drop") %>% 
      distinct() %>% 
      group_by(Sample, Genus) %>%   
      summarise(abund = sum(mean_abundance),
            readcount = sum(mean_read_count),
            dnaconc = mean(mean_dna_conc),
            .groups = "drop") %>% 
      arrange(-abund)
    }) %>% 
  bind_rows()
```

```{r Top genus, eval=TRUE, echo=TRUE, include=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
# Most abundant genus from the samples
Top_genus_sample_inhouse_wetsus_2022 = 
  Inhouse_wetsus_2022_studies_mock_ratio %>%
  filter(!Sample %in% mock_names_inhouse_wetsus_2022$Sample) %>% 
  group_by(Genus) %>%
  summarise(mean_abundantie_inhouse_wetsus_2022 = mean(abund)) %>%  
  arrange(desc(mean_abundantie_inhouse_wetsus_2022)) %>%
  slice_head(n = 10)

Top_genus_sample_inhouse_wetsus_2023 = 
  Inhouse_wetsus_2023_studies_mock_ratio %>%
  filter(!Sample %in% mock_names_inhouse_wetsus_2023$Sample) %>% 
  group_by(Genus) %>%
  summarise(mean_abundantie_inhouse_wetsus_2023 = mean(abund)) %>%  
  arrange(desc(mean_abundantie_inhouse_wetsus_2023)) %>%  
  slice_head(n = 10) 

Top_genus_sample_zymo_log10 = 
  Zymo_log10_studies_mock_ratio %>%
  filter(!Sample %in% mock_names_zymo_log10$Sample) %>% 
  group_by(Genus) %>%
  summarise(mean_abundantie_zymo_log10 = mean(abund)) %>% 
  arrange(desc(mean_abundantie_zymo_log10)) %>% 
  slice_head(n = 10) 

Top_genus_sample_zymo_equil = 
  Zymo_equil_studies_mock_ratio %>%
  filter(!Sample %in% mock_names_zymo_equil$Sample) %>% 
  group_by(Genus) %>%
  summarise(mean_abundantie_zymo_equil = mean(abund)) %>% 
  arrange(desc(mean_abundantie_zymo_equil)) %>%  
  slice_head(n = 10)  
```


```{r tabel maken voor plot sampel / mock (mock), eval=TRUE, echo=TRUE, include=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
# calculate mean, sd and cv across all samples for every Genus
table_Inhouse_wetsus_2022_mock_ratio = 
  Inhouse_wetsus_2022_studies_mock_ratio %>% 
  select(Genus, Sample, abund) %>% 
  pivot_wider(names_from = Sample, values_from = abund, values_fill = 0) %>%
  rowwise() %>%   
  mutate(mean = mean(c_across(where(is.numeric) & !matches(all_mock))),
         sd = sd(c_across(where(is.numeric) & !matches(all_mock))),
         CV = sd/mean*100) %>% 
  arrange(-mean) %>% 
  ungroup()

table_Inhouse_wetsus_2023_mock_ratio = 
  Inhouse_wetsus_2023_studies_mock_ratio %>% 
  select(Genus, Sample, abund) %>% 
  pivot_wider(names_from = Sample, values_from = abund, values_fill = 0) %>%
  rowwise() %>%   
  mutate(mean = mean(c_across(where(is.numeric) & !matches(all_mock))),
         sd = sd(c_across(where(is.numeric) & !matches(all_mock))),
         CV = sd/mean*100) %>% 
  arrange(-mean) %>% 
  ungroup()

table_Zymo_log10_mock_ratio = 
  Zymo_log10_studies_mock_ratio %>% 
  select(Genus, Sample, abund) %>% 
  pivot_wider(names_from = Sample, values_from = abund, values_fill = 0) %>%
  rowwise() %>%   
  mutate(mean = mean(c_across(where(is.numeric) & !matches(all_mock))),
         sd = sd(c_across(where(is.numeric) & !matches(all_mock))),
         CV = sd/mean*100) %>% 
  arrange(-mean) %>% 
  ungroup()

table_Zymo_equil_mock_ratio = 
  Zymo_equil_studies_mock_ratio %>% 
  select(Genus, Sample, abund) %>% 
  pivot_wider(names_from = Sample, values_from = abund, values_fill = 0) %>%
  rowwise() %>%   
  mutate(mean = mean(c_across(where(is.numeric) & !matches(all_mock))),
         sd = sd(c_across(where(is.numeric) & !matches(all_mock))),
         CV = sd/mean*100) %>% 
  arrange(-mean) %>% 
  ungroup()

# remove mean, sd, cv from table and also remove mock sampels
# plotting results 
table2_inhouse_wetsus_2022_mock_ratio =
  table_Inhouse_wetsus_2022_mock_ratio %>% 
  filter((Genus %in% Top_genus_sample_inhouse_wetsus_2022$Genus)) %>%
  select(-mean, -sd, -CV) %>% 
  pivot_longer(cols = -c(Genus), names_to = "Sample", values_to = "abund") %>% 
  left_join(., Inhouse_wetsus_2022_studies_mock_ratio %>% 
              select(Sample, dnaconc) %>% 
              distinct(), by = "Sample") %>% 
  filter(!Sample %in% sample_names_inhouse_wetsus_2022$Sample)

table2_inhouse_wetsus_2023_mock_ratio =
table_Inhouse_wetsus_2023_mock_ratio %>% 
  filter((Genus %in% Top_genus_sample_inhouse_wetsus_2023$Genus)) %>% 
  select(-mean, -sd, -CV) %>% 
  pivot_longer(cols = -c(Genus), names_to = "Sample", values_to = "abund") %>% 
  left_join(., Inhouse_wetsus_2023_studies_mock_ratio %>% select(Sample, dnaconc) %>% distinct(), by = "Sample") %>% 
   filter(!Sample %in% sample_names_inhouse_wetsus_2023$Sample)

table2_zymo_log10_mock_ratio =
table_Zymo_log10_mock_ratio %>% 
  filter((Genus %in% Top_genus_sample_zymo_log10$Genus)) %>%
  select(-mean, -sd, -CV) %>% 
  pivot_longer(cols = -c(Genus), names_to = "Sample", values_to = "abund") %>% 
  left_join(., Zymo_log10_studies_mock_ratio %>% select(Sample, dnaconc) %>% distinct(), by = "Sample") %>% 
   filter(!Sample %in% sample_names_zymo_log10$Sample)

table2_zymo_equil_mock_ratio =
table_Zymo_equil_mock_ratio %>% 
  filter((Genus %in% Top_genus_sample_zymo_equil$Genus)) %>%
  select(-mean, -sd, -CV) %>% 
  pivot_longer(cols = -c(Genus), names_to = "Sample", values_to = "abund") %>% 
  left_join(., Zymo_equil_studies_mock_ratio %>% select(Sample, dnaconc) %>% distinct(), by = "Sample") %>% 
  filter(!Sample %in% sample_names_zymo_equil$Sample)
```

```{r grafiek plotten voor sample / mock (mock), eval=TRUE, echo=TRUE, include=TRUE, message=FALSE, warning=FALSE, cache=TRUE}
# plot inhouse_wetsus_2022
plot_inhouse_wetsus_2022_mock_ratio =
  ggplot(table2_inhouse_wetsus_2022_mock_ratio, aes(x = dnaconc, y = abund, title)) + 
  geom_point(aes(color = Genus), position = position_dodge(width = 0.5)) + 
  facet_wrap(~Genus) +
  scale_y_continuous(transform = "log2") +
  geom_smooth(method = "lm", se = F, color = "grey50") +
  theme(axis.text.x = element_text(size = 8)) +
  labs(x = 'Ratio in DNA Concentratie (ng/l)', y = 'Abundantie (%)', title = 'plot_inhouse_wetsus_2022_mock_ratio')

ggsave("figures/plot_inhouse_wetsus_2022_mock_ratio.pdf", plot = plot_inhouse_wetsus_2022_mock_ratio, width = 6, height = 4)
ggsave("figures/plot_inhouse_wetsus_2022_mock_ratio.jpg", plot = plot_inhouse_wetsus_2022_mock_ratio, width = 6, height = 4)

plot_inhouse_wetsus_2022_mock_ratio

# Plot inhouse_wetsus_2023
plot_inhouse_wetsus_2023_mock_ratio =
ggplot(table2_inhouse_wetsus_2023_mock_ratio, aes(x = dnaconc, y = abund)) + 
  geom_point(aes(color = Genus), position = position_dodge(width = 0.5)) + 
  facet_wrap(~Genus) +
  scale_y_continuous(transform = "log2") +
  geom_smooth(method = "lm", se = F, color = "grey50") +
  theme(axis.text.x = element_text(size = 8)) +
  labs(x = 'Ratio in DNA Concentratie (ng/l)', y = 'Abundantie (%)', title = 'plot_inhouse_wetsus_2023_mock_ratio')

ggsave("figures/plot_inhouse_wetsus_2023_mock_ratio.pdf", plot = plot_inhouse_wetsus_2023_mock_ratio, width = 6, height = 4)
ggsave("figures/plot_inhouse_wetsus_2023_mock_ratio.jpg", plot = plot_inhouse_wetsus_2023_mock_ratio, width = 6, height = 4)

plot_inhouse_wetsus_2023_mock_ratio

# plot zymo log10
plot_zymo_log10_mock_ratio =
ggplot(table2_zymo_log10_mock_ratio, aes(x = dnaconc, y = abund)) + 
  geom_point(aes(color = Genus), position = position_dodge(width = 0.5)) + 
  facet_wrap(~Genus) +
  scale_y_continuous(transform = "log2") +
  geom_smooth(method = "lm", se = F, color = "grey50") +
  theme(axis.text.x = element_text(size = 8)) +
  labs(x = 'Ratio in DNA Concentratie (ng/l)', y = 'Abundantie (%)', title = 'plot_zymo_log10_mock_ratio')

ggsave("figures/plot_zymo_log10_mock_ratio.pdf", plot = plot_zymo_log10_mock_ratio, width = 6, height = 4)
ggsave("figures/plot_zymo_log10_mock_ratio.jpg", plot = plot_zymo_log10_mock_ratio, width = 6, height = 4)

plot_zymo_log10_mock_ratio

# plot zymo equil 
plot_zymo_equil_mock_ratio =
ggplot(table2_zymo_equil_mock_ratio, aes(x = dnaconc, y = abund)) + 
  geom_point(aes(color = Genus), position = position_dodge(width = 0.5)) + 
  facet_wrap(~Genus) +
  scale_y_continuous(transform = "log2") +
  geom_smooth(method = "lm", se = F, color = "grey50") +
  theme(axis.text.x = element_text(size = 8)) +
  labs(x = 'Ratio in DNA Concentratie (ng/l)', y = 'Abundantie (%)', title = 'plot_zymo_equil_mock_ratio')

ggsave("figures/plot_zymo_equil_mock_ratio.pdf", plot = plot_zymo_equil_mock_ratio, width = 6, height = 4)
ggsave("figures/plot_zymo_equil_mock_ratio.jpg", plot = plot_zymo_equil_mock_ratio, width = 6, height = 4)

plot_zymo_equil_mock_ratio
```
